// automatically generated by the FlatBuffers compiler, do not modify
// swiftlint:disable all
// swiftformat:disable all

import FlatBuffers

public enum RemoteShutter_CommandAction: Int8, Enum, Verifiable {
  public typealias T = Int8
  public static var byteSize: Int { return MemoryLayout<Int8>.size }
  public var value: Int8 { return self.rawValue }
  case takepicture = 0
  case toggletorch = 1
  case toggleflash = 2
  case togglecamera = 3
  case setzoom = 4
  case switchlens = 5
  case startrecording = 6
  case stoprecording = 7
  case requestcapabilities = 8
  case settorchmode = 9
  case setflashmode = 10
  case requestframe = 11
  case peerbecamecamera = 12
  case peerbecamemonitor = 13
  case setvideoquality = 14
  case setphotoquality = 15
  case timercountdown = 16
  case syncmonitorsettings = 17
  case setaspectratio = 18

  public static var max: RemoteShutter_CommandAction { return .setaspectratio }
  public static var min: RemoteShutter_CommandAction { return .takepicture }
}


public enum RemoteShutter_CameraPosition: Int8, Enum, Verifiable {
  public typealias T = Int8
  public static var byteSize: Int { return MemoryLayout<Int8>.size }
  public var value: Int8 { return self.rawValue }
  case back = 0
  case front = 1

  public static var max: RemoteShutter_CameraPosition { return .front }
  public static var min: RemoteShutter_CameraPosition { return .back }
}


public enum RemoteShutter_TorchMode: Int8, Enum, Verifiable {
  public typealias T = Int8
  public static var byteSize: Int { return MemoryLayout<Int8>.size }
  public var value: Int8 { return self.rawValue }
  case off = 0
  case on = 1
  case auto = 2

  public static var max: RemoteShutter_TorchMode { return .auto }
  public static var min: RemoteShutter_TorchMode { return .off }
}


public enum RemoteShutter_FlashMode: Int8, Enum, Verifiable {
  public typealias T = Int8
  public static var byteSize: Int { return MemoryLayout<Int8>.size }
  public var value: Int8 { return self.rawValue }
  case off = 0
  case on = 1
  case auto = 2

  public static var max: RemoteShutter_FlashMode { return .auto }
  public static var min: RemoteShutter_FlashMode { return .off }
}


public enum RemoteShutter_CameraLensType: Int8, Enum, Verifiable {
  public typealias T = Int8
  public static var byteSize: Int { return MemoryLayout<Int8>.size }
  public var value: Int8 { return self.rawValue }
  case wideangle = 0
  case ultrawide = 1
  case telephoto = 2
  case dualcamera = 3

  public static var max: RemoteShutter_CameraLensType { return .dualcamera }
  public static var min: RemoteShutter_CameraLensType { return .wideangle }
}


public enum RemoteShutter_MessageType: Int8, Enum, Verifiable {
  public typealias T = Int8
  public static var byteSize: Int { return MemoryLayout<Int8>.size }
  public var value: Int8 { return self.rawValue }
  case cameracommand = 0
  case camerastateresponse = 1
  case framedata = 2

  public static var max: RemoteShutter_MessageType { return .framedata }
  public static var min: RemoteShutter_MessageType { return .cameracommand }
}


public enum RemoteShutter_VideoResolution: Int8, Enum, Verifiable {
  public typealias T = Int8
  public static var byteSize: Int { return MemoryLayout<Int8>.size }
  public var value: Int8 { return self.rawValue }
  case unknown = 0
  case hd1080p = 1
  case uhd4k = 2

  public static var max: RemoteShutter_VideoResolution { return .uhd4k }
  public static var min: RemoteShutter_VideoResolution { return .unknown }
}


public enum RemoteShutter_VideoFrameRate: Int8, Enum, Verifiable {
  public typealias T = Int8
  public static var byteSize: Int { return MemoryLayout<Int8>.size }
  public var value: Int8 { return self.rawValue }
  case unknown = 0
  case fps24 = 1
  case fps30 = 2
  case fps60 = 3

  public static var max: RemoteShutter_VideoFrameRate { return .fps60 }
  public static var min: RemoteShutter_VideoFrameRate { return .unknown }
}


public enum RemoteShutter_PhotoFormat: Int8, Enum, Verifiable {
  public typealias T = Int8
  public static var byteSize: Int { return MemoryLayout<Int8>.size }
  public var value: Int8 { return self.rawValue }
  case unknown = 0
  case jpeg = 1
  case heif = 2

  public static var max: RemoteShutter_PhotoFormat { return .heif }
  public static var min: RemoteShutter_PhotoFormat { return .unknown }
}


public enum RemoteShutter_HDRMode: Int8, Enum, Verifiable {
  public typealias T = Int8
  public static var byteSize: Int { return MemoryLayout<Int8>.size }
  public var value: Int8 { return self.rawValue }
  case unknown = 0
  case off = 1
  case on = 2

  public static var max: RemoteShutter_HDRMode { return .on }
  public static var min: RemoteShutter_HDRMode { return .unknown }
}


public enum RemoteShutter_RecordingModeEnum: Int8, Enum, Verifiable {
  public typealias T = Int8
  public static var byteSize: Int { return MemoryLayout<Int8>.size }
  public var value: Int8 { return self.rawValue }
  case unknown = 0
  case photo = 1
  case video = 2
  case shorts = 3

  public static var max: RemoteShutter_RecordingModeEnum { return .shorts }
  public static var min: RemoteShutter_RecordingModeEnum { return .unknown }
}


public enum RemoteShutter_AspectRatioEnum: Int8, Enum, Verifiable {
  public typealias T = Int8
  public static var byteSize: Int { return MemoryLayout<Int8>.size }
  public var value: Int8 { return self.rawValue }
  case unknown = 0
  case fourthree = 1
  case sixteennine = 2
  case oneone = 3

  public static var max: RemoteShutter_AspectRatioEnum { return .oneone }
  public static var min: RemoteShutter_AspectRatioEnum { return .unknown }
}


public enum RemoteShutter_WatchCommandAction: Int8, Enum, Verifiable {
  public typealias T = Int8
  public static var byteSize: Int { return MemoryLayout<Int8>.size }
  public var value: Int8 { return self.rawValue }
  case unknown = 0
  case setzoom = 1
  case takepicture = 2
  case startrecording = 3
  case stoprecording = 4
  case switchlens = 5
  case toggleflash = 6
  case toggletorch = 7
  case togglecamera = 8
  case requeststate = 9

  public static var max: RemoteShutter_WatchCommandAction { return .requeststate }
  public static var min: RemoteShutter_WatchCommandAction { return .unknown }
}


public enum RemoteShutter_WatchMessageType: Int8, Enum, Verifiable {
  public typealias T = Int8
  public static var byteSize: Int { return MemoryLayout<Int8>.size }
  public var value: Int8 { return self.rawValue }
  case watchcommandmsg = 0
  case watchstatemsg = 1

  public static var max: RemoteShutter_WatchMessageType { return .watchstatemsg }
  public static var min: RemoteShutter_WatchMessageType { return .watchcommandmsg }
}


public struct RemoteShutter_CommandParameters: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_25_2_10() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  public static var id: String { "RCAM" } 
  public static func finish(_ fbb: inout FlatBufferBuilder, end: Offset, prefix: Bool = false) { fbb.finish(offset: end, fileId: RemoteShutter_CommandParameters.id, addPrefix: prefix) }
  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case sendToRemote = 4
    case zoomFactor = 6
    case lensType = 8
    case torchMode = 10
    case flashMode = 12
    case bundleVersion = 14
    case shortVersion = 16
    case platform = 18
    case videoResolution = 20
    case videoFrameRate = 22
    case photoFormat = 24
    case hdrMode = 26
    case countdownValue = 28
    case recordingMode = 30
    case aspectRatio = 32
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var sendToRemote: Bool { let o = _accessor.offset(VTOFFSET.sendToRemote.v); return o == 0 ? false : _accessor.readBuffer(of: Bool.self, at: o) }
  public var zoomFactor: Double { let o = _accessor.offset(VTOFFSET.zoomFactor.v); return o == 0 ? 0.0 : _accessor.readBuffer(of: Double.self, at: o) }
  public var lensType: RemoteShutter_CameraLensType { let o = _accessor.offset(VTOFFSET.lensType.v); return o == 0 ? .wideangle : RemoteShutter_CameraLensType(rawValue: _accessor.readBuffer(of: Int8.self, at: o)) ?? .wideangle }
  public var torchMode: RemoteShutter_TorchMode { let o = _accessor.offset(VTOFFSET.torchMode.v); return o == 0 ? .off : RemoteShutter_TorchMode(rawValue: _accessor.readBuffer(of: Int8.self, at: o)) ?? .off }
  public var flashMode: RemoteShutter_FlashMode { let o = _accessor.offset(VTOFFSET.flashMode.v); return o == 0 ? .off : RemoteShutter_FlashMode(rawValue: _accessor.readBuffer(of: Int8.self, at: o)) ?? .off }
  public var bundleVersion: Int32 { let o = _accessor.offset(VTOFFSET.bundleVersion.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int32.self, at: o) }
  public var shortVersion: String? { let o = _accessor.offset(VTOFFSET.shortVersion.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var shortVersionSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.shortVersion.v) }
  public var platform: String? { let o = _accessor.offset(VTOFFSET.platform.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var platformSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.platform.v) }
  public var videoResolution: RemoteShutter_VideoResolution { let o = _accessor.offset(VTOFFSET.videoResolution.v); return o == 0 ? .unknown : RemoteShutter_VideoResolution(rawValue: _accessor.readBuffer(of: Int8.self, at: o)) ?? .unknown }
  public var videoFrameRate: RemoteShutter_VideoFrameRate { let o = _accessor.offset(VTOFFSET.videoFrameRate.v); return o == 0 ? .unknown : RemoteShutter_VideoFrameRate(rawValue: _accessor.readBuffer(of: Int8.self, at: o)) ?? .unknown }
  public var photoFormat: RemoteShutter_PhotoFormat { let o = _accessor.offset(VTOFFSET.photoFormat.v); return o == 0 ? .unknown : RemoteShutter_PhotoFormat(rawValue: _accessor.readBuffer(of: Int8.self, at: o)) ?? .unknown }
  public var hdrMode: RemoteShutter_HDRMode { let o = _accessor.offset(VTOFFSET.hdrMode.v); return o == 0 ? .unknown : RemoteShutter_HDRMode(rawValue: _accessor.readBuffer(of: Int8.self, at: o)) ?? .unknown }
  public var countdownValue: Int32 { let o = _accessor.offset(VTOFFSET.countdownValue.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int32.self, at: o) }
  public var recordingMode: RemoteShutter_RecordingModeEnum { let o = _accessor.offset(VTOFFSET.recordingMode.v); return o == 0 ? .unknown : RemoteShutter_RecordingModeEnum(rawValue: _accessor.readBuffer(of: Int8.self, at: o)) ?? .unknown }
  public var aspectRatio: RemoteShutter_AspectRatioEnum { let o = _accessor.offset(VTOFFSET.aspectRatio.v); return o == 0 ? .unknown : RemoteShutter_AspectRatioEnum(rawValue: _accessor.readBuffer(of: Int8.self, at: o)) ?? .unknown }
  public static func startCommandParameters(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 15) }
  public static func add(sendToRemote: Bool, _ fbb: inout FlatBufferBuilder) { fbb.add(element: sendToRemote, def: false,
   at: VTOFFSET.sendToRemote.p) }
  public static func add(zoomFactor: Double, _ fbb: inout FlatBufferBuilder) { fbb.add(element: zoomFactor, def: 0.0, at: VTOFFSET.zoomFactor.p) }
  public static func add(lensType: RemoteShutter_CameraLensType, _ fbb: inout FlatBufferBuilder) { fbb.add(element: lensType.rawValue, def: 0, at: VTOFFSET.lensType.p) }
  public static func add(torchMode: RemoteShutter_TorchMode, _ fbb: inout FlatBufferBuilder) { fbb.add(element: torchMode.rawValue, def: 0, at: VTOFFSET.torchMode.p) }
  public static func add(flashMode: RemoteShutter_FlashMode, _ fbb: inout FlatBufferBuilder) { fbb.add(element: flashMode.rawValue, def: 0, at: VTOFFSET.flashMode.p) }
  public static func add(bundleVersion: Int32, _ fbb: inout FlatBufferBuilder) { fbb.add(element: bundleVersion, def: 0, at: VTOFFSET.bundleVersion.p) }
  public static func add(shortVersion: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: shortVersion, at: VTOFFSET.shortVersion.p) }
  public static func add(platform: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: platform, at: VTOFFSET.platform.p) }
  public static func add(videoResolution: RemoteShutter_VideoResolution, _ fbb: inout FlatBufferBuilder) { fbb.add(element: videoResolution.rawValue, def: 0, at: VTOFFSET.videoResolution.p) }
  public static func add(videoFrameRate: RemoteShutter_VideoFrameRate, _ fbb: inout FlatBufferBuilder) { fbb.add(element: videoFrameRate.rawValue, def: 0, at: VTOFFSET.videoFrameRate.p) }
  public static func add(photoFormat: RemoteShutter_PhotoFormat, _ fbb: inout FlatBufferBuilder) { fbb.add(element: photoFormat.rawValue, def: 0, at: VTOFFSET.photoFormat.p) }
  public static func add(hdrMode: RemoteShutter_HDRMode, _ fbb: inout FlatBufferBuilder) { fbb.add(element: hdrMode.rawValue, def: 0, at: VTOFFSET.hdrMode.p) }
  public static func add(countdownValue: Int32, _ fbb: inout FlatBufferBuilder) { fbb.add(element: countdownValue, def: 0, at: VTOFFSET.countdownValue.p) }
  public static func add(recordingMode: RemoteShutter_RecordingModeEnum, _ fbb: inout FlatBufferBuilder) { fbb.add(element: recordingMode.rawValue, def: 0, at: VTOFFSET.recordingMode.p) }
  public static func add(aspectRatio: RemoteShutter_AspectRatioEnum, _ fbb: inout FlatBufferBuilder) { fbb.add(element: aspectRatio.rawValue, def: 0, at: VTOFFSET.aspectRatio.p) }
  public static func endCommandParameters(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createCommandParameters(
    _ fbb: inout FlatBufferBuilder,
    sendToRemote: Bool = false,
    zoomFactor: Double = 0.0,
    lensType: RemoteShutter_CameraLensType = .wideangle,
    torchMode: RemoteShutter_TorchMode = .off,
    flashMode: RemoteShutter_FlashMode = .off,
    bundleVersion: Int32 = 0,
    shortVersionOffset shortVersion: Offset = Offset(),
    platformOffset platform: Offset = Offset(),
    videoResolution: RemoteShutter_VideoResolution = .unknown,
    videoFrameRate: RemoteShutter_VideoFrameRate = .unknown,
    photoFormat: RemoteShutter_PhotoFormat = .unknown,
    hdrMode: RemoteShutter_HDRMode = .unknown,
    countdownValue: Int32 = 0,
    recordingMode: RemoteShutter_RecordingModeEnum = .unknown,
    aspectRatio: RemoteShutter_AspectRatioEnum = .unknown
  ) -> Offset {
    let __start = RemoteShutter_CommandParameters.startCommandParameters(&fbb)
    RemoteShutter_CommandParameters.add(sendToRemote: sendToRemote, &fbb)
    RemoteShutter_CommandParameters.add(zoomFactor: zoomFactor, &fbb)
    RemoteShutter_CommandParameters.add(lensType: lensType, &fbb)
    RemoteShutter_CommandParameters.add(torchMode: torchMode, &fbb)
    RemoteShutter_CommandParameters.add(flashMode: flashMode, &fbb)
    RemoteShutter_CommandParameters.add(bundleVersion: bundleVersion, &fbb)
    RemoteShutter_CommandParameters.add(shortVersion: shortVersion, &fbb)
    RemoteShutter_CommandParameters.add(platform: platform, &fbb)
    RemoteShutter_CommandParameters.add(videoResolution: videoResolution, &fbb)
    RemoteShutter_CommandParameters.add(videoFrameRate: videoFrameRate, &fbb)
    RemoteShutter_CommandParameters.add(photoFormat: photoFormat, &fbb)
    RemoteShutter_CommandParameters.add(hdrMode: hdrMode, &fbb)
    RemoteShutter_CommandParameters.add(countdownValue: countdownValue, &fbb)
    RemoteShutter_CommandParameters.add(recordingMode: recordingMode, &fbb)
    RemoteShutter_CommandParameters.add(aspectRatio: aspectRatio, &fbb)
    return RemoteShutter_CommandParameters.endCommandParameters(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.sendToRemote.p, fieldName: "sendToRemote", required: false, type: Bool.self)
    try _v.visit(field: VTOFFSET.zoomFactor.p, fieldName: "zoomFactor", required: false, type: Double.self)
    try _v.visit(field: VTOFFSET.lensType.p, fieldName: "lensType", required: false, type: RemoteShutter_CameraLensType.self)
    try _v.visit(field: VTOFFSET.torchMode.p, fieldName: "torchMode", required: false, type: RemoteShutter_TorchMode.self)
    try _v.visit(field: VTOFFSET.flashMode.p, fieldName: "flashMode", required: false, type: RemoteShutter_FlashMode.self)
    try _v.visit(field: VTOFFSET.bundleVersion.p, fieldName: "bundleVersion", required: false, type: Int32.self)
    try _v.visit(field: VTOFFSET.shortVersion.p, fieldName: "shortVersion", required: false, type: ForwardOffset<String>.self)
    try _v.visit(field: VTOFFSET.platform.p, fieldName: "platform", required: false, type: ForwardOffset<String>.self)
    try _v.visit(field: VTOFFSET.videoResolution.p, fieldName: "videoResolution", required: false, type: RemoteShutter_VideoResolution.self)
    try _v.visit(field: VTOFFSET.videoFrameRate.p, fieldName: "videoFrameRate", required: false, type: RemoteShutter_VideoFrameRate.self)
    try _v.visit(field: VTOFFSET.photoFormat.p, fieldName: "photoFormat", required: false, type: RemoteShutter_PhotoFormat.self)
    try _v.visit(field: VTOFFSET.hdrMode.p, fieldName: "hdrMode", required: false, type: RemoteShutter_HDRMode.self)
    try _v.visit(field: VTOFFSET.countdownValue.p, fieldName: "countdownValue", required: false, type: Int32.self)
    try _v.visit(field: VTOFFSET.recordingMode.p, fieldName: "recordingMode", required: false, type: RemoteShutter_RecordingModeEnum.self)
    try _v.visit(field: VTOFFSET.aspectRatio.p, fieldName: "aspectRatio", required: false, type: RemoteShutter_AspectRatioEnum.self)
    _v.finish()
  }
}

public struct RemoteShutter_CameraCommand: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_25_2_10() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  public static var id: String { "RCAM" } 
  public static func finish(_ fbb: inout FlatBufferBuilder, end: Offset, prefix: Bool = false) { fbb.finish(offset: end, fileId: RemoteShutter_CameraCommand.id, addPrefix: prefix) }
  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case action = 4
    case parameters = 6
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var action: RemoteShutter_CommandAction { let o = _accessor.offset(VTOFFSET.action.v); return o == 0 ? .takepicture : RemoteShutter_CommandAction(rawValue: _accessor.readBuffer(of: Int8.self, at: o)) ?? .takepicture }
  public var parameters: RemoteShutter_CommandParameters? { let o = _accessor.offset(VTOFFSET.parameters.v); return o == 0 ? nil : RemoteShutter_CommandParameters(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public static func startCameraCommand(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 2) }
  public static func add(action: RemoteShutter_CommandAction, _ fbb: inout FlatBufferBuilder) { fbb.add(element: action.rawValue, def: 0, at: VTOFFSET.action.p) }
  public static func add(parameters: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: parameters, at: VTOFFSET.parameters.p) }
  public static func endCameraCommand(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createCameraCommand(
    _ fbb: inout FlatBufferBuilder,
    action: RemoteShutter_CommandAction = .takepicture,
    parametersOffset parameters: Offset = Offset()
  ) -> Offset {
    let __start = RemoteShutter_CameraCommand.startCameraCommand(&fbb)
    RemoteShutter_CameraCommand.add(action: action, &fbb)
    RemoteShutter_CameraCommand.add(parameters: parameters, &fbb)
    return RemoteShutter_CameraCommand.endCameraCommand(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.action.p, fieldName: "action", required: false, type: RemoteShutter_CommandAction.self)
    try _v.visit(field: VTOFFSET.parameters.p, fieldName: "parameters", required: false, type: ForwardOffset<RemoteShutter_CommandParameters>.self)
    _v.finish()
  }
}

public struct RemoteShutter_ZoomRange: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_25_2_10() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  public static var id: String { "RCAM" } 
  public static func finish(_ fbb: inout FlatBufferBuilder, end: Offset, prefix: Bool = false) { fbb.finish(offset: end, fileId: RemoteShutter_ZoomRange.id, addPrefix: prefix) }
  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case minZoom = 4
    case maxZoom = 6
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var minZoom: Double { let o = _accessor.offset(VTOFFSET.minZoom.v); return o == 0 ? 0.0 : _accessor.readBuffer(of: Double.self, at: o) }
  public var maxZoom: Double { let o = _accessor.offset(VTOFFSET.maxZoom.v); return o == 0 ? 0.0 : _accessor.readBuffer(of: Double.self, at: o) }
  public static func startZoomRange(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 2) }
  public static func add(minZoom: Double, _ fbb: inout FlatBufferBuilder) { fbb.add(element: minZoom, def: 0.0, at: VTOFFSET.minZoom.p) }
  public static func add(maxZoom: Double, _ fbb: inout FlatBufferBuilder) { fbb.add(element: maxZoom, def: 0.0, at: VTOFFSET.maxZoom.p) }
  public static func endZoomRange(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createZoomRange(
    _ fbb: inout FlatBufferBuilder,
    minZoom: Double = 0.0,
    maxZoom: Double = 0.0
  ) -> Offset {
    let __start = RemoteShutter_ZoomRange.startZoomRange(&fbb)
    RemoteShutter_ZoomRange.add(minZoom: minZoom, &fbb)
    RemoteShutter_ZoomRange.add(maxZoom: maxZoom, &fbb)
    return RemoteShutter_ZoomRange.endZoomRange(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.minZoom.p, fieldName: "minZoom", required: false, type: Double.self)
    try _v.visit(field: VTOFFSET.maxZoom.p, fieldName: "maxZoom", required: false, type: Double.self)
    _v.finish()
  }
}

public struct RemoteShutter_ZoomCapability: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_25_2_10() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  public static var id: String { "RCAM" } 
  public static func finish(_ fbb: inout FlatBufferBuilder, end: Offset, prefix: Bool = false) { fbb.finish(offset: end, fileId: RemoteShutter_ZoomCapability.id, addPrefix: prefix) }
  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case lensType = 4
    case zoomRange = 6
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var lensType: RemoteShutter_CameraLensType { let o = _accessor.offset(VTOFFSET.lensType.v); return o == 0 ? .wideangle : RemoteShutter_CameraLensType(rawValue: _accessor.readBuffer(of: Int8.self, at: o)) ?? .wideangle }
  public var zoomRange: RemoteShutter_ZoomRange? { let o = _accessor.offset(VTOFFSET.zoomRange.v); return o == 0 ? nil : RemoteShutter_ZoomRange(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public static func startZoomCapability(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 2) }
  public static func add(lensType: RemoteShutter_CameraLensType, _ fbb: inout FlatBufferBuilder) { fbb.add(element: lensType.rawValue, def: 0, at: VTOFFSET.lensType.p) }
  public static func add(zoomRange: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: zoomRange, at: VTOFFSET.zoomRange.p) }
  public static func endZoomCapability(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createZoomCapability(
    _ fbb: inout FlatBufferBuilder,
    lensType: RemoteShutter_CameraLensType = .wideangle,
    zoomRangeOffset zoomRange: Offset = Offset()
  ) -> Offset {
    let __start = RemoteShutter_ZoomCapability.startZoomCapability(&fbb)
    RemoteShutter_ZoomCapability.add(lensType: lensType, &fbb)
    RemoteShutter_ZoomCapability.add(zoomRange: zoomRange, &fbb)
    return RemoteShutter_ZoomCapability.endZoomCapability(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.lensType.p, fieldName: "lensType", required: false, type: RemoteShutter_CameraLensType.self)
    try _v.visit(field: VTOFFSET.zoomRange.p, fieldName: "zoomRange", required: false, type: ForwardOffset<RemoteShutter_ZoomRange>.self)
    _v.finish()
  }
}

public struct RemoteShutter_ResolutionFrameRates: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_25_2_10() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  public static var id: String { "RCAM" } 
  public static func finish(_ fbb: inout FlatBufferBuilder, end: Offset, prefix: Bool = false) { fbb.finish(offset: end, fileId: RemoteShutter_ResolutionFrameRates.id, addPrefix: prefix) }
  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case resolution = 4
    case supportedFrameRates = 6
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var resolution: RemoteShutter_VideoResolution { let o = _accessor.offset(VTOFFSET.resolution.v); return o == 0 ? .unknown : RemoteShutter_VideoResolution(rawValue: _accessor.readBuffer(of: Int8.self, at: o)) ?? .unknown }
  public var hasSupportedFrameRates: Bool { let o = _accessor.offset(VTOFFSET.supportedFrameRates.v); return o == 0 ? false : true }
  public var supportedFrameRatesCount: Int32 { let o = _accessor.offset(VTOFFSET.supportedFrameRates.v); return o == 0 ? 0 : _accessor.vector(count: o) }
  public func supportedFrameRates(at index: Int32) -> RemoteShutter_VideoFrameRate? { let o = _accessor.offset(VTOFFSET.supportedFrameRates.v); return o == 0 ? RemoteShutter_VideoFrameRate.unknown : RemoteShutter_VideoFrameRate(rawValue: _accessor.directRead(of: Int8.self, offset: _accessor.vector(at: o) + index * 1)) }
  public static func startResolutionFrameRates(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 2) }
  public static func add(resolution: RemoteShutter_VideoResolution, _ fbb: inout FlatBufferBuilder) { fbb.add(element: resolution.rawValue, def: 0, at: VTOFFSET.resolution.p) }
  public static func addVectorOf(supportedFrameRates: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: supportedFrameRates, at: VTOFFSET.supportedFrameRates.p) }
  public static func endResolutionFrameRates(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createResolutionFrameRates(
    _ fbb: inout FlatBufferBuilder,
    resolution: RemoteShutter_VideoResolution = .unknown,
    supportedFrameRatesVectorOffset supportedFrameRates: Offset = Offset()
  ) -> Offset {
    let __start = RemoteShutter_ResolutionFrameRates.startResolutionFrameRates(&fbb)
    RemoteShutter_ResolutionFrameRates.add(resolution: resolution, &fbb)
    RemoteShutter_ResolutionFrameRates.addVectorOf(supportedFrameRates: supportedFrameRates, &fbb)
    return RemoteShutter_ResolutionFrameRates.endResolutionFrameRates(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.resolution.p, fieldName: "resolution", required: false, type: RemoteShutter_VideoResolution.self)
    try _v.visit(field: VTOFFSET.supportedFrameRates.p, fieldName: "supportedFrameRates", required: false, type: ForwardOffset<Vector<RemoteShutter_VideoFrameRate, RemoteShutter_VideoFrameRate>>.self)
    _v.finish()
  }
}

public struct RemoteShutter_VideoQualityCapabilities: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_25_2_10() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  public static var id: String { "RCAM" } 
  public static func finish(_ fbb: inout FlatBufferBuilder, end: Offset, prefix: Bool = false) { fbb.finish(offset: end, fileId: RemoteShutter_VideoQualityCapabilities.id, addPrefix: prefix) }
  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case supportedResolutions = 4
    case supportedFrameRates = 6
    case resolutionFrameRates = 8
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var hasSupportedResolutions: Bool { let o = _accessor.offset(VTOFFSET.supportedResolutions.v); return o == 0 ? false : true }
  public var supportedResolutionsCount: Int32 { let o = _accessor.offset(VTOFFSET.supportedResolutions.v); return o == 0 ? 0 : _accessor.vector(count: o) }
  public func supportedResolutions(at index: Int32) -> RemoteShutter_VideoResolution? { let o = _accessor.offset(VTOFFSET.supportedResolutions.v); return o == 0 ? RemoteShutter_VideoResolution.unknown : RemoteShutter_VideoResolution(rawValue: _accessor.directRead(of: Int8.self, offset: _accessor.vector(at: o) + index * 1)) }
  public var hasSupportedFrameRates: Bool { let o = _accessor.offset(VTOFFSET.supportedFrameRates.v); return o == 0 ? false : true }
  public var supportedFrameRatesCount: Int32 { let o = _accessor.offset(VTOFFSET.supportedFrameRates.v); return o == 0 ? 0 : _accessor.vector(count: o) }
  public func supportedFrameRates(at index: Int32) -> RemoteShutter_VideoFrameRate? { let o = _accessor.offset(VTOFFSET.supportedFrameRates.v); return o == 0 ? RemoteShutter_VideoFrameRate.unknown : RemoteShutter_VideoFrameRate(rawValue: _accessor.directRead(of: Int8.self, offset: _accessor.vector(at: o) + index * 1)) }
  public var hasResolutionFrameRates: Bool { let o = _accessor.offset(VTOFFSET.resolutionFrameRates.v); return o == 0 ? false : true }
  public var resolutionFrameRatesCount: Int32 { let o = _accessor.offset(VTOFFSET.resolutionFrameRates.v); return o == 0 ? 0 : _accessor.vector(count: o) }
  public func resolutionFrameRates(at index: Int32) -> RemoteShutter_ResolutionFrameRates? { let o = _accessor.offset(VTOFFSET.resolutionFrameRates.v); return o == 0 ? nil : RemoteShutter_ResolutionFrameRates(_accessor.bb, o: _accessor.indirect(_accessor.vector(at: o) + index * 4)) }
  public static func startVideoQualityCapabilities(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 3) }
  public static func addVectorOf(supportedResolutions: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: supportedResolutions, at: VTOFFSET.supportedResolutions.p) }
  public static func addVectorOf(supportedFrameRates: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: supportedFrameRates, at: VTOFFSET.supportedFrameRates.p) }
  public static func addVectorOf(resolutionFrameRates: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: resolutionFrameRates, at: VTOFFSET.resolutionFrameRates.p) }
  public static func endVideoQualityCapabilities(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createVideoQualityCapabilities(
    _ fbb: inout FlatBufferBuilder,
    supportedResolutionsVectorOffset supportedResolutions: Offset = Offset(),
    supportedFrameRatesVectorOffset supportedFrameRates: Offset = Offset(),
    resolutionFrameRatesVectorOffset resolutionFrameRates: Offset = Offset()
  ) -> Offset {
    let __start = RemoteShutter_VideoQualityCapabilities.startVideoQualityCapabilities(&fbb)
    RemoteShutter_VideoQualityCapabilities.addVectorOf(supportedResolutions: supportedResolutions, &fbb)
    RemoteShutter_VideoQualityCapabilities.addVectorOf(supportedFrameRates: supportedFrameRates, &fbb)
    RemoteShutter_VideoQualityCapabilities.addVectorOf(resolutionFrameRates: resolutionFrameRates, &fbb)
    return RemoteShutter_VideoQualityCapabilities.endVideoQualityCapabilities(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.supportedResolutions.p, fieldName: "supportedResolutions", required: false, type: ForwardOffset<Vector<RemoteShutter_VideoResolution, RemoteShutter_VideoResolution>>.self)
    try _v.visit(field: VTOFFSET.supportedFrameRates.p, fieldName: "supportedFrameRates", required: false, type: ForwardOffset<Vector<RemoteShutter_VideoFrameRate, RemoteShutter_VideoFrameRate>>.self)
    try _v.visit(field: VTOFFSET.resolutionFrameRates.p, fieldName: "resolutionFrameRates", required: false, type: ForwardOffset<Vector<ForwardOffset<RemoteShutter_ResolutionFrameRates>, RemoteShutter_ResolutionFrameRates>>.self)
    _v.finish()
  }
}

public struct RemoteShutter_PhotoQualityCapabilities: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_25_2_10() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  public static var id: String { "RCAM" } 
  public static func finish(_ fbb: inout FlatBufferBuilder, end: Offset, prefix: Bool = false) { fbb.finish(offset: end, fileId: RemoteShutter_PhotoQualityCapabilities.id, addPrefix: prefix) }
  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case supportsHeif = 4
    case supportsHdr = 6
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var supportsHeif: Bool { let o = _accessor.offset(VTOFFSET.supportsHeif.v); return o == 0 ? false : _accessor.readBuffer(of: Bool.self, at: o) }
  public var supportsHdr: Bool { let o = _accessor.offset(VTOFFSET.supportsHdr.v); return o == 0 ? false : _accessor.readBuffer(of: Bool.self, at: o) }
  public static func startPhotoQualityCapabilities(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 2) }
  public static func add(supportsHeif: Bool, _ fbb: inout FlatBufferBuilder) { fbb.add(element: supportsHeif, def: false,
   at: VTOFFSET.supportsHeif.p) }
  public static func add(supportsHdr: Bool, _ fbb: inout FlatBufferBuilder) { fbb.add(element: supportsHdr, def: false,
   at: VTOFFSET.supportsHdr.p) }
  public static func endPhotoQualityCapabilities(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createPhotoQualityCapabilities(
    _ fbb: inout FlatBufferBuilder,
    supportsHeif: Bool = false,
    supportsHdr: Bool = false
  ) -> Offset {
    let __start = RemoteShutter_PhotoQualityCapabilities.startPhotoQualityCapabilities(&fbb)
    RemoteShutter_PhotoQualityCapabilities.add(supportsHeif: supportsHeif, &fbb)
    RemoteShutter_PhotoQualityCapabilities.add(supportsHdr: supportsHdr, &fbb)
    return RemoteShutter_PhotoQualityCapabilities.endPhotoQualityCapabilities(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.supportsHeif.p, fieldName: "supportsHeif", required: false, type: Bool.self)
    try _v.visit(field: VTOFFSET.supportsHdr.p, fieldName: "supportsHdr", required: false, type: Bool.self)
    _v.finish()
  }
}

public struct RemoteShutter_CameraInfo: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_25_2_10() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  public static var id: String { "RCAM" } 
  public static func finish(_ fbb: inout FlatBufferBuilder, end: Offset, prefix: Bool = false) { fbb.finish(offset: end, fileId: RemoteShutter_CameraInfo.id, addPrefix: prefix) }
  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case availableLenses = 4
    case hasFlash = 6
    case hasTorch = 8
    case zoomCapabilities = 10
    case videoQuality = 12
    case photoQuality = 14
    case zoomStops = 16
    case wideAngleZoomFactor = 18
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var hasAvailableLenses: Bool { let o = _accessor.offset(VTOFFSET.availableLenses.v); return o == 0 ? false : true }
  public var availableLensesCount: Int32 { let o = _accessor.offset(VTOFFSET.availableLenses.v); return o == 0 ? 0 : _accessor.vector(count: o) }
  public func availableLenses(at index: Int32) -> RemoteShutter_CameraLensType? { let o = _accessor.offset(VTOFFSET.availableLenses.v); return o == 0 ? RemoteShutter_CameraLensType.wideangle : RemoteShutter_CameraLensType(rawValue: _accessor.directRead(of: Int8.self, offset: _accessor.vector(at: o) + index * 1)) }
  public var hasFlash: Bool { let o = _accessor.offset(VTOFFSET.hasFlash.v); return o == 0 ? false : _accessor.readBuffer(of: Bool.self, at: o) }
  public var hasTorch: Bool { let o = _accessor.offset(VTOFFSET.hasTorch.v); return o == 0 ? false : _accessor.readBuffer(of: Bool.self, at: o) }
  public var hasZoomCapabilities: Bool { let o = _accessor.offset(VTOFFSET.zoomCapabilities.v); return o == 0 ? false : true }
  public var zoomCapabilitiesCount: Int32 { let o = _accessor.offset(VTOFFSET.zoomCapabilities.v); return o == 0 ? 0 : _accessor.vector(count: o) }
  public func zoomCapabilities(at index: Int32) -> RemoteShutter_ZoomCapability? { let o = _accessor.offset(VTOFFSET.zoomCapabilities.v); return o == 0 ? nil : RemoteShutter_ZoomCapability(_accessor.bb, o: _accessor.indirect(_accessor.vector(at: o) + index * 4)) }
  public var videoQuality: RemoteShutter_VideoQualityCapabilities? { let o = _accessor.offset(VTOFFSET.videoQuality.v); return o == 0 ? nil : RemoteShutter_VideoQualityCapabilities(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public var photoQuality: RemoteShutter_PhotoQualityCapabilities? { let o = _accessor.offset(VTOFFSET.photoQuality.v); return o == 0 ? nil : RemoteShutter_PhotoQualityCapabilities(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public var hasZoomStops: Bool { let o = _accessor.offset(VTOFFSET.zoomStops.v); return o == 0 ? false : true }
  public var zoomStopsCount: Int32 { let o = _accessor.offset(VTOFFSET.zoomStops.v); return o == 0 ? 0 : _accessor.vector(count: o) }
  public func zoomStops(at index: Int32) -> Double { let o = _accessor.offset(VTOFFSET.zoomStops.v); return o == 0 ? 0 : _accessor.directRead(of: Double.self, offset: _accessor.vector(at: o) + index * 8) }
  public var zoomStops: [Double] { return _accessor.getVector(at: VTOFFSET.zoomStops.v) ?? [] }
  public var wideAngleZoomFactor: Double { let o = _accessor.offset(VTOFFSET.wideAngleZoomFactor.v); return o == 0 ? 0.0 : _accessor.readBuffer(of: Double.self, at: o) }
  public static func startCameraInfo(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 8) }
  public static func addVectorOf(availableLenses: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: availableLenses, at: VTOFFSET.availableLenses.p) }
  public static func add(hasFlash: Bool, _ fbb: inout FlatBufferBuilder) { fbb.add(element: hasFlash, def: false,
   at: VTOFFSET.hasFlash.p) }
  public static func add(hasTorch: Bool, _ fbb: inout FlatBufferBuilder) { fbb.add(element: hasTorch, def: false,
   at: VTOFFSET.hasTorch.p) }
  public static func addVectorOf(zoomCapabilities: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: zoomCapabilities, at: VTOFFSET.zoomCapabilities.p) }
  public static func add(videoQuality: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: videoQuality, at: VTOFFSET.videoQuality.p) }
  public static func add(photoQuality: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: photoQuality, at: VTOFFSET.photoQuality.p) }
  public static func addVectorOf(zoomStops: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: zoomStops, at: VTOFFSET.zoomStops.p) }
  public static func add(wideAngleZoomFactor: Double, _ fbb: inout FlatBufferBuilder) { fbb.add(element: wideAngleZoomFactor, def: 0.0, at: VTOFFSET.wideAngleZoomFactor.p) }
  public static func endCameraInfo(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createCameraInfo(
    _ fbb: inout FlatBufferBuilder,
    availableLensesVectorOffset availableLenses: Offset = Offset(),
    hasFlash: Bool = false,
    hasTorch: Bool = false,
    zoomCapabilitiesVectorOffset zoomCapabilities: Offset = Offset(),
    videoQualityOffset videoQuality: Offset = Offset(),
    photoQualityOffset photoQuality: Offset = Offset(),
    zoomStopsVectorOffset zoomStops: Offset = Offset(),
    wideAngleZoomFactor: Double = 0.0
  ) -> Offset {
    let __start = RemoteShutter_CameraInfo.startCameraInfo(&fbb)
    RemoteShutter_CameraInfo.addVectorOf(availableLenses: availableLenses, &fbb)
    RemoteShutter_CameraInfo.add(hasFlash: hasFlash, &fbb)
    RemoteShutter_CameraInfo.add(hasTorch: hasTorch, &fbb)
    RemoteShutter_CameraInfo.addVectorOf(zoomCapabilities: zoomCapabilities, &fbb)
    RemoteShutter_CameraInfo.add(videoQuality: videoQuality, &fbb)
    RemoteShutter_CameraInfo.add(photoQuality: photoQuality, &fbb)
    RemoteShutter_CameraInfo.addVectorOf(zoomStops: zoomStops, &fbb)
    RemoteShutter_CameraInfo.add(wideAngleZoomFactor: wideAngleZoomFactor, &fbb)
    return RemoteShutter_CameraInfo.endCameraInfo(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.availableLenses.p, fieldName: "availableLenses", required: false, type: ForwardOffset<Vector<RemoteShutter_CameraLensType, RemoteShutter_CameraLensType>>.self)
    try _v.visit(field: VTOFFSET.hasFlash.p, fieldName: "hasFlash", required: false, type: Bool.self)
    try _v.visit(field: VTOFFSET.hasTorch.p, fieldName: "hasTorch", required: false, type: Bool.self)
    try _v.visit(field: VTOFFSET.zoomCapabilities.p, fieldName: "zoomCapabilities", required: false, type: ForwardOffset<Vector<ForwardOffset<RemoteShutter_ZoomCapability>, RemoteShutter_ZoomCapability>>.self)
    try _v.visit(field: VTOFFSET.videoQuality.p, fieldName: "videoQuality", required: false, type: ForwardOffset<RemoteShutter_VideoQualityCapabilities>.self)
    try _v.visit(field: VTOFFSET.photoQuality.p, fieldName: "photoQuality", required: false, type: ForwardOffset<RemoteShutter_PhotoQualityCapabilities>.self)
    try _v.visit(field: VTOFFSET.zoomStops.p, fieldName: "zoomStops", required: false, type: ForwardOffset<Vector<Double, Double>>.self)
    try _v.visit(field: VTOFFSET.wideAngleZoomFactor.p, fieldName: "wideAngleZoomFactor", required: false, type: Double.self)
    _v.finish()
  }
}

public struct RemoteShutter_CameraState: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_25_2_10() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  public static var id: String { "RCAM" } 
  public static func finish(_ fbb: inout FlatBufferBuilder, end: Offset, prefix: Bool = false) { fbb.finish(offset: end, fileId: RemoteShutter_CameraState.id, addPrefix: prefix) }
  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case currentCamera = 4
    case currentLens = 6
    case zoomFactor = 8
    case torchMode = 10
    case flashMode = 12
    case videoResolution = 14
    case videoFrameRate = 16
    case photoFormat = 18
    case hdrMode = 20
    case aspectRatio = 22
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var currentCamera: RemoteShutter_CameraPosition { let o = _accessor.offset(VTOFFSET.currentCamera.v); return o == 0 ? .back : RemoteShutter_CameraPosition(rawValue: _accessor.readBuffer(of: Int8.self, at: o)) ?? .back }
  public var currentLens: RemoteShutter_CameraLensType { let o = _accessor.offset(VTOFFSET.currentLens.v); return o == 0 ? .wideangle : RemoteShutter_CameraLensType(rawValue: _accessor.readBuffer(of: Int8.self, at: o)) ?? .wideangle }
  public var zoomFactor: Double { let o = _accessor.offset(VTOFFSET.zoomFactor.v); return o == 0 ? 0.0 : _accessor.readBuffer(of: Double.self, at: o) }
  public var torchMode: RemoteShutter_TorchMode { let o = _accessor.offset(VTOFFSET.torchMode.v); return o == 0 ? .off : RemoteShutter_TorchMode(rawValue: _accessor.readBuffer(of: Int8.self, at: o)) ?? .off }
  public var flashMode: RemoteShutter_FlashMode { let o = _accessor.offset(VTOFFSET.flashMode.v); return o == 0 ? .off : RemoteShutter_FlashMode(rawValue: _accessor.readBuffer(of: Int8.self, at: o)) ?? .off }
  public var videoResolution: RemoteShutter_VideoResolution { let o = _accessor.offset(VTOFFSET.videoResolution.v); return o == 0 ? .unknown : RemoteShutter_VideoResolution(rawValue: _accessor.readBuffer(of: Int8.self, at: o)) ?? .unknown }
  public var videoFrameRate: RemoteShutter_VideoFrameRate { let o = _accessor.offset(VTOFFSET.videoFrameRate.v); return o == 0 ? .unknown : RemoteShutter_VideoFrameRate(rawValue: _accessor.readBuffer(of: Int8.self, at: o)) ?? .unknown }
  public var photoFormat: RemoteShutter_PhotoFormat { let o = _accessor.offset(VTOFFSET.photoFormat.v); return o == 0 ? .unknown : RemoteShutter_PhotoFormat(rawValue: _accessor.readBuffer(of: Int8.self, at: o)) ?? .unknown }
  public var hdrMode: RemoteShutter_HDRMode { let o = _accessor.offset(VTOFFSET.hdrMode.v); return o == 0 ? .unknown : RemoteShutter_HDRMode(rawValue: _accessor.readBuffer(of: Int8.self, at: o)) ?? .unknown }
  public var aspectRatio: RemoteShutter_AspectRatioEnum { let o = _accessor.offset(VTOFFSET.aspectRatio.v); return o == 0 ? .unknown : RemoteShutter_AspectRatioEnum(rawValue: _accessor.readBuffer(of: Int8.self, at: o)) ?? .unknown }
  public static func startCameraState(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 10) }
  public static func add(currentCamera: RemoteShutter_CameraPosition, _ fbb: inout FlatBufferBuilder) { fbb.add(element: currentCamera.rawValue, def: 0, at: VTOFFSET.currentCamera.p) }
  public static func add(currentLens: RemoteShutter_CameraLensType, _ fbb: inout FlatBufferBuilder) { fbb.add(element: currentLens.rawValue, def: 0, at: VTOFFSET.currentLens.p) }
  public static func add(zoomFactor: Double, _ fbb: inout FlatBufferBuilder) { fbb.add(element: zoomFactor, def: 0.0, at: VTOFFSET.zoomFactor.p) }
  public static func add(torchMode: RemoteShutter_TorchMode, _ fbb: inout FlatBufferBuilder) { fbb.add(element: torchMode.rawValue, def: 0, at: VTOFFSET.torchMode.p) }
  public static func add(flashMode: RemoteShutter_FlashMode, _ fbb: inout FlatBufferBuilder) { fbb.add(element: flashMode.rawValue, def: 0, at: VTOFFSET.flashMode.p) }
  public static func add(videoResolution: RemoteShutter_VideoResolution, _ fbb: inout FlatBufferBuilder) { fbb.add(element: videoResolution.rawValue, def: 0, at: VTOFFSET.videoResolution.p) }
  public static func add(videoFrameRate: RemoteShutter_VideoFrameRate, _ fbb: inout FlatBufferBuilder) { fbb.add(element: videoFrameRate.rawValue, def: 0, at: VTOFFSET.videoFrameRate.p) }
  public static func add(photoFormat: RemoteShutter_PhotoFormat, _ fbb: inout FlatBufferBuilder) { fbb.add(element: photoFormat.rawValue, def: 0, at: VTOFFSET.photoFormat.p) }
  public static func add(hdrMode: RemoteShutter_HDRMode, _ fbb: inout FlatBufferBuilder) { fbb.add(element: hdrMode.rawValue, def: 0, at: VTOFFSET.hdrMode.p) }
  public static func add(aspectRatio: RemoteShutter_AspectRatioEnum, _ fbb: inout FlatBufferBuilder) { fbb.add(element: aspectRatio.rawValue, def: 0, at: VTOFFSET.aspectRatio.p) }
  public static func endCameraState(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createCameraState(
    _ fbb: inout FlatBufferBuilder,
    currentCamera: RemoteShutter_CameraPosition = .back,
    currentLens: RemoteShutter_CameraLensType = .wideangle,
    zoomFactor: Double = 0.0,
    torchMode: RemoteShutter_TorchMode = .off,
    flashMode: RemoteShutter_FlashMode = .off,
    videoResolution: RemoteShutter_VideoResolution = .unknown,
    videoFrameRate: RemoteShutter_VideoFrameRate = .unknown,
    photoFormat: RemoteShutter_PhotoFormat = .unknown,
    hdrMode: RemoteShutter_HDRMode = .unknown,
    aspectRatio: RemoteShutter_AspectRatioEnum = .unknown
  ) -> Offset {
    let __start = RemoteShutter_CameraState.startCameraState(&fbb)
    RemoteShutter_CameraState.add(currentCamera: currentCamera, &fbb)
    RemoteShutter_CameraState.add(currentLens: currentLens, &fbb)
    RemoteShutter_CameraState.add(zoomFactor: zoomFactor, &fbb)
    RemoteShutter_CameraState.add(torchMode: torchMode, &fbb)
    RemoteShutter_CameraState.add(flashMode: flashMode, &fbb)
    RemoteShutter_CameraState.add(videoResolution: videoResolution, &fbb)
    RemoteShutter_CameraState.add(videoFrameRate: videoFrameRate, &fbb)
    RemoteShutter_CameraState.add(photoFormat: photoFormat, &fbb)
    RemoteShutter_CameraState.add(hdrMode: hdrMode, &fbb)
    RemoteShutter_CameraState.add(aspectRatio: aspectRatio, &fbb)
    return RemoteShutter_CameraState.endCameraState(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.currentCamera.p, fieldName: "currentCamera", required: false, type: RemoteShutter_CameraPosition.self)
    try _v.visit(field: VTOFFSET.currentLens.p, fieldName: "currentLens", required: false, type: RemoteShutter_CameraLensType.self)
    try _v.visit(field: VTOFFSET.zoomFactor.p, fieldName: "zoomFactor", required: false, type: Double.self)
    try _v.visit(field: VTOFFSET.torchMode.p, fieldName: "torchMode", required: false, type: RemoteShutter_TorchMode.self)
    try _v.visit(field: VTOFFSET.flashMode.p, fieldName: "flashMode", required: false, type: RemoteShutter_FlashMode.self)
    try _v.visit(field: VTOFFSET.videoResolution.p, fieldName: "videoResolution", required: false, type: RemoteShutter_VideoResolution.self)
    try _v.visit(field: VTOFFSET.videoFrameRate.p, fieldName: "videoFrameRate", required: false, type: RemoteShutter_VideoFrameRate.self)
    try _v.visit(field: VTOFFSET.photoFormat.p, fieldName: "photoFormat", required: false, type: RemoteShutter_PhotoFormat.self)
    try _v.visit(field: VTOFFSET.hdrMode.p, fieldName: "hdrMode", required: false, type: RemoteShutter_HDRMode.self)
    try _v.visit(field: VTOFFSET.aspectRatio.p, fieldName: "aspectRatio", required: false, type: RemoteShutter_AspectRatioEnum.self)
    _v.finish()
  }
}

public struct RemoteShutter_CameraCapabilities: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_25_2_10() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  public static var id: String { "RCAM" } 
  public static func finish(_ fbb: inout FlatBufferBuilder, end: Offset, prefix: Bool = false) { fbb.finish(offset: end, fileId: RemoteShutter_CameraCapabilities.id, addPrefix: prefix) }
  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case frontCamera = 4
    case backCamera = 6
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var frontCamera: RemoteShutter_CameraInfo? { let o = _accessor.offset(VTOFFSET.frontCamera.v); return o == 0 ? nil : RemoteShutter_CameraInfo(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public var backCamera: RemoteShutter_CameraInfo? { let o = _accessor.offset(VTOFFSET.backCamera.v); return o == 0 ? nil : RemoteShutter_CameraInfo(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public static func startCameraCapabilities(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 2) }
  public static func add(frontCamera: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: frontCamera, at: VTOFFSET.frontCamera.p) }
  public static func add(backCamera: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: backCamera, at: VTOFFSET.backCamera.p) }
  public static func endCameraCapabilities(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createCameraCapabilities(
    _ fbb: inout FlatBufferBuilder,
    frontCameraOffset frontCamera: Offset = Offset(),
    backCameraOffset backCamera: Offset = Offset()
  ) -> Offset {
    let __start = RemoteShutter_CameraCapabilities.startCameraCapabilities(&fbb)
    RemoteShutter_CameraCapabilities.add(frontCamera: frontCamera, &fbb)
    RemoteShutter_CameraCapabilities.add(backCamera: backCamera, &fbb)
    return RemoteShutter_CameraCapabilities.endCameraCapabilities(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.frontCamera.p, fieldName: "frontCamera", required: false, type: ForwardOffset<RemoteShutter_CameraInfo>.self)
    try _v.visit(field: VTOFFSET.backCamera.p, fieldName: "backCamera", required: false, type: ForwardOffset<RemoteShutter_CameraInfo>.self)
    _v.finish()
  }
}

public struct RemoteShutter_CameraStateResponse: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_25_2_10() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  public static var id: String { "RCAM" } 
  public static func finish(_ fbb: inout FlatBufferBuilder, end: Offset, prefix: Bool = false) { fbb.finish(offset: end, fileId: RemoteShutter_CameraStateResponse.id, addPrefix: prefix) }
  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case action = 4
    case success = 6
    case error = 8
    case currentState = 10
    case capabilities = 12
    case mediaData = 14
    case recordingStartTime = 16
    case availableLenses = 18
    case zoomRange = 20
    case currentZoom = 22
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var action: RemoteShutter_CommandAction { let o = _accessor.offset(VTOFFSET.action.v); return o == 0 ? .takepicture : RemoteShutter_CommandAction(rawValue: _accessor.readBuffer(of: Int8.self, at: o)) ?? .takepicture }
  public var success: Bool { let o = _accessor.offset(VTOFFSET.success.v); return o == 0 ? false : _accessor.readBuffer(of: Bool.self, at: o) }
  public var error: String? { let o = _accessor.offset(VTOFFSET.error.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var errorSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.error.v) }
  public var currentState: RemoteShutter_CameraState? { let o = _accessor.offset(VTOFFSET.currentState.v); return o == 0 ? nil : RemoteShutter_CameraState(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public var capabilities: RemoteShutter_CameraCapabilities? { let o = _accessor.offset(VTOFFSET.capabilities.v); return o == 0 ? nil : RemoteShutter_CameraCapabilities(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public var hasMediaData: Bool { let o = _accessor.offset(VTOFFSET.mediaData.v); return o == 0 ? false : true }
  public var mediaDataCount: Int32 { let o = _accessor.offset(VTOFFSET.mediaData.v); return o == 0 ? 0 : _accessor.vector(count: o) }
  public func mediaData(at index: Int32) -> UInt8 { let o = _accessor.offset(VTOFFSET.mediaData.v); return o == 0 ? 0 : _accessor.directRead(of: UInt8.self, offset: _accessor.vector(at: o) + index * 1) }
  public var mediaData: [UInt8] { return _accessor.getVector(at: VTOFFSET.mediaData.v) ?? [] }
  public var recordingStartTime: UInt64 { let o = _accessor.offset(VTOFFSET.recordingStartTime.v); return o == 0 ? 0 : _accessor.readBuffer(of: UInt64.self, at: o) }
  public var hasAvailableLenses: Bool { let o = _accessor.offset(VTOFFSET.availableLenses.v); return o == 0 ? false : true }
  public var availableLensesCount: Int32 { let o = _accessor.offset(VTOFFSET.availableLenses.v); return o == 0 ? 0 : _accessor.vector(count: o) }
  public func availableLenses(at index: Int32) -> RemoteShutter_CameraLensType? { let o = _accessor.offset(VTOFFSET.availableLenses.v); return o == 0 ? RemoteShutter_CameraLensType.wideangle : RemoteShutter_CameraLensType(rawValue: _accessor.directRead(of: Int8.self, offset: _accessor.vector(at: o) + index * 1)) }
  public var zoomRange: RemoteShutter_ZoomRange? { let o = _accessor.offset(VTOFFSET.zoomRange.v); return o == 0 ? nil : RemoteShutter_ZoomRange(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public var currentZoom: Double { let o = _accessor.offset(VTOFFSET.currentZoom.v); return o == 0 ? 0.0 : _accessor.readBuffer(of: Double.self, at: o) }
  public static func startCameraStateResponse(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 10) }
  public static func add(action: RemoteShutter_CommandAction, _ fbb: inout FlatBufferBuilder) { fbb.add(element: action.rawValue, def: 0, at: VTOFFSET.action.p) }
  public static func add(success: Bool, _ fbb: inout FlatBufferBuilder) { fbb.add(element: success, def: false,
   at: VTOFFSET.success.p) }
  public static func add(error: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: error, at: VTOFFSET.error.p) }
  public static func add(currentState: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: currentState, at: VTOFFSET.currentState.p) }
  public static func add(capabilities: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: capabilities, at: VTOFFSET.capabilities.p) }
  public static func addVectorOf(mediaData: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: mediaData, at: VTOFFSET.mediaData.p) }
  public static func add(recordingStartTime: UInt64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: recordingStartTime, def: 0, at: VTOFFSET.recordingStartTime.p) }
  public static func addVectorOf(availableLenses: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: availableLenses, at: VTOFFSET.availableLenses.p) }
  public static func add(zoomRange: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: zoomRange, at: VTOFFSET.zoomRange.p) }
  public static func add(currentZoom: Double, _ fbb: inout FlatBufferBuilder) { fbb.add(element: currentZoom, def: 0.0, at: VTOFFSET.currentZoom.p) }
  public static func endCameraStateResponse(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createCameraStateResponse(
    _ fbb: inout FlatBufferBuilder,
    action: RemoteShutter_CommandAction = .takepicture,
    success: Bool = false,
    errorOffset error: Offset = Offset(),
    currentStateOffset currentState: Offset = Offset(),
    capabilitiesOffset capabilities: Offset = Offset(),
    mediaDataVectorOffset mediaData: Offset = Offset(),
    recordingStartTime: UInt64 = 0,
    availableLensesVectorOffset availableLenses: Offset = Offset(),
    zoomRangeOffset zoomRange: Offset = Offset(),
    currentZoom: Double = 0.0
  ) -> Offset {
    let __start = RemoteShutter_CameraStateResponse.startCameraStateResponse(&fbb)
    RemoteShutter_CameraStateResponse.add(action: action, &fbb)
    RemoteShutter_CameraStateResponse.add(success: success, &fbb)
    RemoteShutter_CameraStateResponse.add(error: error, &fbb)
    RemoteShutter_CameraStateResponse.add(currentState: currentState, &fbb)
    RemoteShutter_CameraStateResponse.add(capabilities: capabilities, &fbb)
    RemoteShutter_CameraStateResponse.addVectorOf(mediaData: mediaData, &fbb)
    RemoteShutter_CameraStateResponse.add(recordingStartTime: recordingStartTime, &fbb)
    RemoteShutter_CameraStateResponse.addVectorOf(availableLenses: availableLenses, &fbb)
    RemoteShutter_CameraStateResponse.add(zoomRange: zoomRange, &fbb)
    RemoteShutter_CameraStateResponse.add(currentZoom: currentZoom, &fbb)
    return RemoteShutter_CameraStateResponse.endCameraStateResponse(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.action.p, fieldName: "action", required: false, type: RemoteShutter_CommandAction.self)
    try _v.visit(field: VTOFFSET.success.p, fieldName: "success", required: false, type: Bool.self)
    try _v.visit(field: VTOFFSET.error.p, fieldName: "error", required: false, type: ForwardOffset<String>.self)
    try _v.visit(field: VTOFFSET.currentState.p, fieldName: "currentState", required: false, type: ForwardOffset<RemoteShutter_CameraState>.self)
    try _v.visit(field: VTOFFSET.capabilities.p, fieldName: "capabilities", required: false, type: ForwardOffset<RemoteShutter_CameraCapabilities>.self)
    try _v.visit(field: VTOFFSET.mediaData.p, fieldName: "mediaData", required: false, type: ForwardOffset<Vector<UInt8, UInt8>>.self)
    try _v.visit(field: VTOFFSET.recordingStartTime.p, fieldName: "recordingStartTime", required: false, type: UInt64.self)
    try _v.visit(field: VTOFFSET.availableLenses.p, fieldName: "availableLenses", required: false, type: ForwardOffset<Vector<RemoteShutter_CameraLensType, RemoteShutter_CameraLensType>>.self)
    try _v.visit(field: VTOFFSET.zoomRange.p, fieldName: "zoomRange", required: false, type: ForwardOffset<RemoteShutter_ZoomRange>.self)
    try _v.visit(field: VTOFFSET.currentZoom.p, fieldName: "currentZoom", required: false, type: Double.self)
    _v.finish()
  }
}

public struct RemoteShutter_FrameData: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_25_2_10() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  public static var id: String { "RCAM" } 
  public static func finish(_ fbb: inout FlatBufferBuilder, end: Offset, prefix: Bool = false) { fbb.finish(offset: end, fileId: RemoteShutter_FrameData.id, addPrefix: prefix) }
  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case imageData = 4
    case fps = 6
    case cameraPosition = 8
    case orientation = 10
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var hasImageData: Bool { let o = _accessor.offset(VTOFFSET.imageData.v); return o == 0 ? false : true }
  public var imageDataCount: Int32 { let o = _accessor.offset(VTOFFSET.imageData.v); return o == 0 ? 0 : _accessor.vector(count: o) }
  public func imageData(at index: Int32) -> UInt8 { let o = _accessor.offset(VTOFFSET.imageData.v); return o == 0 ? 0 : _accessor.directRead(of: UInt8.self, offset: _accessor.vector(at: o) + index * 1) }
  public var imageData: [UInt8] { return _accessor.getVector(at: VTOFFSET.imageData.v) ?? [] }
  public var fps: Int32 { let o = _accessor.offset(VTOFFSET.fps.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int32.self, at: o) }
  public var cameraPosition: RemoteShutter_CameraPosition { let o = _accessor.offset(VTOFFSET.cameraPosition.v); return o == 0 ? .back : RemoteShutter_CameraPosition(rawValue: _accessor.readBuffer(of: Int8.self, at: o)) ?? .back }
  public var orientation: Int32 { let o = _accessor.offset(VTOFFSET.orientation.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int32.self, at: o) }
  public static func startFrameData(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 4) }
  public static func addVectorOf(imageData: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: imageData, at: VTOFFSET.imageData.p) }
  public static func add(fps: Int32, _ fbb: inout FlatBufferBuilder) { fbb.add(element: fps, def: 0, at: VTOFFSET.fps.p) }
  public static func add(cameraPosition: RemoteShutter_CameraPosition, _ fbb: inout FlatBufferBuilder) { fbb.add(element: cameraPosition.rawValue, def: 0, at: VTOFFSET.cameraPosition.p) }
  public static func add(orientation: Int32, _ fbb: inout FlatBufferBuilder) { fbb.add(element: orientation, def: 0, at: VTOFFSET.orientation.p) }
  public static func endFrameData(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createFrameData(
    _ fbb: inout FlatBufferBuilder,
    imageDataVectorOffset imageData: Offset = Offset(),
    fps: Int32 = 0,
    cameraPosition: RemoteShutter_CameraPosition = .back,
    orientation: Int32 = 0
  ) -> Offset {
    let __start = RemoteShutter_FrameData.startFrameData(&fbb)
    RemoteShutter_FrameData.addVectorOf(imageData: imageData, &fbb)
    RemoteShutter_FrameData.add(fps: fps, &fbb)
    RemoteShutter_FrameData.add(cameraPosition: cameraPosition, &fbb)
    RemoteShutter_FrameData.add(orientation: orientation, &fbb)
    return RemoteShutter_FrameData.endFrameData(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.imageData.p, fieldName: "imageData", required: false, type: ForwardOffset<Vector<UInt8, UInt8>>.self)
    try _v.visit(field: VTOFFSET.fps.p, fieldName: "fps", required: false, type: Int32.self)
    try _v.visit(field: VTOFFSET.cameraPosition.p, fieldName: "cameraPosition", required: false, type: RemoteShutter_CameraPosition.self)
    try _v.visit(field: VTOFFSET.orientation.p, fieldName: "orientation", required: false, type: Int32.self)
    _v.finish()
  }
}

public struct RemoteShutter_P2PMessage: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_25_2_10() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  public static var id: String { "RCAM" } 
  public static func finish(_ fbb: inout FlatBufferBuilder, end: Offset, prefix: Bool = false) { fbb.finish(offset: end, fileId: RemoteShutter_P2PMessage.id, addPrefix: prefix) }
  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case type = 4
    case command = 6
    case response = 8
    case frameData = 10
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var type: RemoteShutter_MessageType { let o = _accessor.offset(VTOFFSET.type.v); return o == 0 ? .cameracommand : RemoteShutter_MessageType(rawValue: _accessor.readBuffer(of: Int8.self, at: o)) ?? .cameracommand }
  public var command: RemoteShutter_CameraCommand? { let o = _accessor.offset(VTOFFSET.command.v); return o == 0 ? nil : RemoteShutter_CameraCommand(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public var response: RemoteShutter_CameraStateResponse? { let o = _accessor.offset(VTOFFSET.response.v); return o == 0 ? nil : RemoteShutter_CameraStateResponse(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public var frameData: RemoteShutter_FrameData? { let o = _accessor.offset(VTOFFSET.frameData.v); return o == 0 ? nil : RemoteShutter_FrameData(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public static func startP2PMessage(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 4) }
  public static func add(type: RemoteShutter_MessageType, _ fbb: inout FlatBufferBuilder) { fbb.add(element: type.rawValue, def: 0, at: VTOFFSET.type.p) }
  public static func add(command: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: command, at: VTOFFSET.command.p) }
  public static func add(response: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: response, at: VTOFFSET.response.p) }
  public static func add(frameData: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: frameData, at: VTOFFSET.frameData.p) }
  public static func endP2PMessage(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createP2PMessage(
    _ fbb: inout FlatBufferBuilder,
    type: RemoteShutter_MessageType = .cameracommand,
    commandOffset command: Offset = Offset(),
    responseOffset response: Offset = Offset(),
    frameDataOffset frameData: Offset = Offset()
  ) -> Offset {
    let __start = RemoteShutter_P2PMessage.startP2PMessage(&fbb)
    RemoteShutter_P2PMessage.add(type: type, &fbb)
    RemoteShutter_P2PMessage.add(command: command, &fbb)
    RemoteShutter_P2PMessage.add(response: response, &fbb)
    RemoteShutter_P2PMessage.add(frameData: frameData, &fbb)
    return RemoteShutter_P2PMessage.endP2PMessage(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.type.p, fieldName: "type", required: false, type: RemoteShutter_MessageType.self)
    try _v.visit(field: VTOFFSET.command.p, fieldName: "command", required: false, type: ForwardOffset<RemoteShutter_CameraCommand>.self)
    try _v.visit(field: VTOFFSET.response.p, fieldName: "response", required: false, type: ForwardOffset<RemoteShutter_CameraStateResponse>.self)
    try _v.visit(field: VTOFFSET.frameData.p, fieldName: "frameData", required: false, type: ForwardOffset<RemoteShutter_FrameData>.self)
    _v.finish()
  }
}

public struct RemoteShutter_WatchCommand: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_25_2_10() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  public static var id: String { "RCAM" } 
  public static func finish(_ fbb: inout FlatBufferBuilder, end: Offset, prefix: Bool = false) { fbb.finish(offset: end, fileId: RemoteShutter_WatchCommand.id, addPrefix: prefix) }
  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case action = 4
    case zoomFactor = 6
    case lensType = 8
    case timerSeconds = 10
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var action: RemoteShutter_WatchCommandAction { let o = _accessor.offset(VTOFFSET.action.v); return o == 0 ? .unknown : RemoteShutter_WatchCommandAction(rawValue: _accessor.readBuffer(of: Int8.self, at: o)) ?? .unknown }
  public var zoomFactor: Double { let o = _accessor.offset(VTOFFSET.zoomFactor.v); return o == 0 ? 0.0 : _accessor.readBuffer(of: Double.self, at: o) }
  public var lensType: RemoteShutter_CameraLensType { let o = _accessor.offset(VTOFFSET.lensType.v); return o == 0 ? .wideangle : RemoteShutter_CameraLensType(rawValue: _accessor.readBuffer(of: Int8.self, at: o)) ?? .wideangle }
  public var timerSeconds: Int32 { let o = _accessor.offset(VTOFFSET.timerSeconds.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int32.self, at: o) }
  public static func startWatchCommand(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 4) }
  public static func add(action: RemoteShutter_WatchCommandAction, _ fbb: inout FlatBufferBuilder) { fbb.add(element: action.rawValue, def: 0, at: VTOFFSET.action.p) }
  public static func add(zoomFactor: Double, _ fbb: inout FlatBufferBuilder) { fbb.add(element: zoomFactor, def: 0.0, at: VTOFFSET.zoomFactor.p) }
  public static func add(lensType: RemoteShutter_CameraLensType, _ fbb: inout FlatBufferBuilder) { fbb.add(element: lensType.rawValue, def: 0, at: VTOFFSET.lensType.p) }
  public static func add(timerSeconds: Int32, _ fbb: inout FlatBufferBuilder) { fbb.add(element: timerSeconds, def: 0, at: VTOFFSET.timerSeconds.p) }
  public static func endWatchCommand(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createWatchCommand(
    _ fbb: inout FlatBufferBuilder,
    action: RemoteShutter_WatchCommandAction = .unknown,
    zoomFactor: Double = 0.0,
    lensType: RemoteShutter_CameraLensType = .wideangle,
    timerSeconds: Int32 = 0
  ) -> Offset {
    let __start = RemoteShutter_WatchCommand.startWatchCommand(&fbb)
    RemoteShutter_WatchCommand.add(action: action, &fbb)
    RemoteShutter_WatchCommand.add(zoomFactor: zoomFactor, &fbb)
    RemoteShutter_WatchCommand.add(lensType: lensType, &fbb)
    RemoteShutter_WatchCommand.add(timerSeconds: timerSeconds, &fbb)
    return RemoteShutter_WatchCommand.endWatchCommand(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.action.p, fieldName: "action", required: false, type: RemoteShutter_WatchCommandAction.self)
    try _v.visit(field: VTOFFSET.zoomFactor.p, fieldName: "zoomFactor", required: false, type: Double.self)
    try _v.visit(field: VTOFFSET.lensType.p, fieldName: "lensType", required: false, type: RemoteShutter_CameraLensType.self)
    try _v.visit(field: VTOFFSET.timerSeconds.p, fieldName: "timerSeconds", required: false, type: Int32.self)
    _v.finish()
  }
}

public struct RemoteShutter_WatchCameraState: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_25_2_10() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  public static var id: String { "RCAM" } 
  public static func finish(_ fbb: inout FlatBufferBuilder, end: Offset, prefix: Bool = false) { fbb.finish(offset: end, fileId: RemoteShutter_WatchCameraState.id, addPrefix: prefix) }
  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case isReady = 4
    case currentZoomFactor = 6
    case minZoomFactor = 8
    case maxZoomFactor = 10
    case isRecording = 12
    case currentMode = 14
    case currentLensType = 16
    case availableLensTypes = 18
    case isFlashEnabled = 20
    case isTorchEnabled = 22
    case zoomStops = 24
    case wideAngleZoomFactor = 26
    case lastEvent = 28
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var isReady: Bool { let o = _accessor.offset(VTOFFSET.isReady.v); return o == 0 ? false : _accessor.readBuffer(of: Bool.self, at: o) }
  public var currentZoomFactor: Double { let o = _accessor.offset(VTOFFSET.currentZoomFactor.v); return o == 0 ? 0.0 : _accessor.readBuffer(of: Double.self, at: o) }
  public var minZoomFactor: Double { let o = _accessor.offset(VTOFFSET.minZoomFactor.v); return o == 0 ? 0.0 : _accessor.readBuffer(of: Double.self, at: o) }
  public var maxZoomFactor: Double { let o = _accessor.offset(VTOFFSET.maxZoomFactor.v); return o == 0 ? 0.0 : _accessor.readBuffer(of: Double.self, at: o) }
  public var isRecording: Bool { let o = _accessor.offset(VTOFFSET.isRecording.v); return o == 0 ? false : _accessor.readBuffer(of: Bool.self, at: o) }
  public var currentMode: RemoteShutter_RecordingModeEnum { let o = _accessor.offset(VTOFFSET.currentMode.v); return o == 0 ? .unknown : RemoteShutter_RecordingModeEnum(rawValue: _accessor.readBuffer(of: Int8.self, at: o)) ?? .unknown }
  public var currentLensType: RemoteShutter_CameraLensType { let o = _accessor.offset(VTOFFSET.currentLensType.v); return o == 0 ? .wideangle : RemoteShutter_CameraLensType(rawValue: _accessor.readBuffer(of: Int8.self, at: o)) ?? .wideangle }
  public var hasAvailableLensTypes: Bool { let o = _accessor.offset(VTOFFSET.availableLensTypes.v); return o == 0 ? false : true }
  public var availableLensTypesCount: Int32 { let o = _accessor.offset(VTOFFSET.availableLensTypes.v); return o == 0 ? 0 : _accessor.vector(count: o) }
  public func availableLensTypes(at index: Int32) -> RemoteShutter_CameraLensType? { let o = _accessor.offset(VTOFFSET.availableLensTypes.v); return o == 0 ? RemoteShutter_CameraLensType.wideangle : RemoteShutter_CameraLensType(rawValue: _accessor.directRead(of: Int8.self, offset: _accessor.vector(at: o) + index * 1)) }
  public var isFlashEnabled: Bool { let o = _accessor.offset(VTOFFSET.isFlashEnabled.v); return o == 0 ? false : _accessor.readBuffer(of: Bool.self, at: o) }
  public var isTorchEnabled: Bool { let o = _accessor.offset(VTOFFSET.isTorchEnabled.v); return o == 0 ? false : _accessor.readBuffer(of: Bool.self, at: o) }
  public var hasZoomStops: Bool { let o = _accessor.offset(VTOFFSET.zoomStops.v); return o == 0 ? false : true }
  public var zoomStopsCount: Int32 { let o = _accessor.offset(VTOFFSET.zoomStops.v); return o == 0 ? 0 : _accessor.vector(count: o) }
  public func zoomStops(at index: Int32) -> Double { let o = _accessor.offset(VTOFFSET.zoomStops.v); return o == 0 ? 0 : _accessor.directRead(of: Double.self, offset: _accessor.vector(at: o) + index * 8) }
  public var zoomStops: [Double] { return _accessor.getVector(at: VTOFFSET.zoomStops.v) ?? [] }
  public var wideAngleZoomFactor: Double { let o = _accessor.offset(VTOFFSET.wideAngleZoomFactor.v); return o == 0 ? 0.0 : _accessor.readBuffer(of: Double.self, at: o) }
  public var lastEvent: String? { let o = _accessor.offset(VTOFFSET.lastEvent.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var lastEventSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.lastEvent.v) }
  public static func startWatchCameraState(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 13) }
  public static func add(isReady: Bool, _ fbb: inout FlatBufferBuilder) { fbb.add(element: isReady, def: false,
   at: VTOFFSET.isReady.p) }
  public static func add(currentZoomFactor: Double, _ fbb: inout FlatBufferBuilder) { fbb.add(element: currentZoomFactor, def: 0.0, at: VTOFFSET.currentZoomFactor.p) }
  public static func add(minZoomFactor: Double, _ fbb: inout FlatBufferBuilder) { fbb.add(element: minZoomFactor, def: 0.0, at: VTOFFSET.minZoomFactor.p) }
  public static func add(maxZoomFactor: Double, _ fbb: inout FlatBufferBuilder) { fbb.add(element: maxZoomFactor, def: 0.0, at: VTOFFSET.maxZoomFactor.p) }
  public static func add(isRecording: Bool, _ fbb: inout FlatBufferBuilder) { fbb.add(element: isRecording, def: false,
   at: VTOFFSET.isRecording.p) }
  public static func add(currentMode: RemoteShutter_RecordingModeEnum, _ fbb: inout FlatBufferBuilder) { fbb.add(element: currentMode.rawValue, def: 0, at: VTOFFSET.currentMode.p) }
  public static func add(currentLensType: RemoteShutter_CameraLensType, _ fbb: inout FlatBufferBuilder) { fbb.add(element: currentLensType.rawValue, def: 0, at: VTOFFSET.currentLensType.p) }
  public static func addVectorOf(availableLensTypes: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: availableLensTypes, at: VTOFFSET.availableLensTypes.p) }
  public static func add(isFlashEnabled: Bool, _ fbb: inout FlatBufferBuilder) { fbb.add(element: isFlashEnabled, def: false,
   at: VTOFFSET.isFlashEnabled.p) }
  public static func add(isTorchEnabled: Bool, _ fbb: inout FlatBufferBuilder) { fbb.add(element: isTorchEnabled, def: false,
   at: VTOFFSET.isTorchEnabled.p) }
  public static func addVectorOf(zoomStops: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: zoomStops, at: VTOFFSET.zoomStops.p) }
  public static func add(wideAngleZoomFactor: Double, _ fbb: inout FlatBufferBuilder) { fbb.add(element: wideAngleZoomFactor, def: 0.0, at: VTOFFSET.wideAngleZoomFactor.p) }
  public static func add(lastEvent: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: lastEvent, at: VTOFFSET.lastEvent.p) }
  public static func endWatchCameraState(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createWatchCameraState(
    _ fbb: inout FlatBufferBuilder,
    isReady: Bool = false,
    currentZoomFactor: Double = 0.0,
    minZoomFactor: Double = 0.0,
    maxZoomFactor: Double = 0.0,
    isRecording: Bool = false,
    currentMode: RemoteShutter_RecordingModeEnum = .unknown,
    currentLensType: RemoteShutter_CameraLensType = .wideangle,
    availableLensTypesVectorOffset availableLensTypes: Offset = Offset(),
    isFlashEnabled: Bool = false,
    isTorchEnabled: Bool = false,
    zoomStopsVectorOffset zoomStops: Offset = Offset(),
    wideAngleZoomFactor: Double = 0.0,
    lastEventOffset lastEvent: Offset = Offset()
  ) -> Offset {
    let __start = RemoteShutter_WatchCameraState.startWatchCameraState(&fbb)
    RemoteShutter_WatchCameraState.add(isReady: isReady, &fbb)
    RemoteShutter_WatchCameraState.add(currentZoomFactor: currentZoomFactor, &fbb)
    RemoteShutter_WatchCameraState.add(minZoomFactor: minZoomFactor, &fbb)
    RemoteShutter_WatchCameraState.add(maxZoomFactor: maxZoomFactor, &fbb)
    RemoteShutter_WatchCameraState.add(isRecording: isRecording, &fbb)
    RemoteShutter_WatchCameraState.add(currentMode: currentMode, &fbb)
    RemoteShutter_WatchCameraState.add(currentLensType: currentLensType, &fbb)
    RemoteShutter_WatchCameraState.addVectorOf(availableLensTypes: availableLensTypes, &fbb)
    RemoteShutter_WatchCameraState.add(isFlashEnabled: isFlashEnabled, &fbb)
    RemoteShutter_WatchCameraState.add(isTorchEnabled: isTorchEnabled, &fbb)
    RemoteShutter_WatchCameraState.addVectorOf(zoomStops: zoomStops, &fbb)
    RemoteShutter_WatchCameraState.add(wideAngleZoomFactor: wideAngleZoomFactor, &fbb)
    RemoteShutter_WatchCameraState.add(lastEvent: lastEvent, &fbb)
    return RemoteShutter_WatchCameraState.endWatchCameraState(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.isReady.p, fieldName: "isReady", required: false, type: Bool.self)
    try _v.visit(field: VTOFFSET.currentZoomFactor.p, fieldName: "currentZoomFactor", required: false, type: Double.self)
    try _v.visit(field: VTOFFSET.minZoomFactor.p, fieldName: "minZoomFactor", required: false, type: Double.self)
    try _v.visit(field: VTOFFSET.maxZoomFactor.p, fieldName: "maxZoomFactor", required: false, type: Double.self)
    try _v.visit(field: VTOFFSET.isRecording.p, fieldName: "isRecording", required: false, type: Bool.self)
    try _v.visit(field: VTOFFSET.currentMode.p, fieldName: "currentMode", required: false, type: RemoteShutter_RecordingModeEnum.self)
    try _v.visit(field: VTOFFSET.currentLensType.p, fieldName: "currentLensType", required: false, type: RemoteShutter_CameraLensType.self)
    try _v.visit(field: VTOFFSET.availableLensTypes.p, fieldName: "availableLensTypes", required: false, type: ForwardOffset<Vector<RemoteShutter_CameraLensType, RemoteShutter_CameraLensType>>.self)
    try _v.visit(field: VTOFFSET.isFlashEnabled.p, fieldName: "isFlashEnabled", required: false, type: Bool.self)
    try _v.visit(field: VTOFFSET.isTorchEnabled.p, fieldName: "isTorchEnabled", required: false, type: Bool.self)
    try _v.visit(field: VTOFFSET.zoomStops.p, fieldName: "zoomStops", required: false, type: ForwardOffset<Vector<Double, Double>>.self)
    try _v.visit(field: VTOFFSET.wideAngleZoomFactor.p, fieldName: "wideAngleZoomFactor", required: false, type: Double.self)
    try _v.visit(field: VTOFFSET.lastEvent.p, fieldName: "lastEvent", required: false, type: ForwardOffset<String>.self)
    _v.finish()
  }
}

public struct RemoteShutter_WatchMessage: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_25_2_10() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  public static var id: String { "RCAM" } 
  public static func finish(_ fbb: inout FlatBufferBuilder, end: Offset, prefix: Bool = false) { fbb.finish(offset: end, fileId: RemoteShutter_WatchMessage.id, addPrefix: prefix) }
  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case type = 4
    case command = 6
    case state = 8
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var type: RemoteShutter_WatchMessageType { let o = _accessor.offset(VTOFFSET.type.v); return o == 0 ? .watchcommandmsg : RemoteShutter_WatchMessageType(rawValue: _accessor.readBuffer(of: Int8.self, at: o)) ?? .watchcommandmsg }
  public var command: RemoteShutter_WatchCommand? { let o = _accessor.offset(VTOFFSET.command.v); return o == 0 ? nil : RemoteShutter_WatchCommand(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public var state: RemoteShutter_WatchCameraState? { let o = _accessor.offset(VTOFFSET.state.v); return o == 0 ? nil : RemoteShutter_WatchCameraState(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public static func startWatchMessage(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 3) }
  public static func add(type: RemoteShutter_WatchMessageType, _ fbb: inout FlatBufferBuilder) { fbb.add(element: type.rawValue, def: 0, at: VTOFFSET.type.p) }
  public static func add(command: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: command, at: VTOFFSET.command.p) }
  public static func add(state: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: state, at: VTOFFSET.state.p) }
  public static func endWatchMessage(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createWatchMessage(
    _ fbb: inout FlatBufferBuilder,
    type: RemoteShutter_WatchMessageType = .watchcommandmsg,
    commandOffset command: Offset = Offset(),
    stateOffset state: Offset = Offset()
  ) -> Offset {
    let __start = RemoteShutter_WatchMessage.startWatchMessage(&fbb)
    RemoteShutter_WatchMessage.add(type: type, &fbb)
    RemoteShutter_WatchMessage.add(command: command, &fbb)
    RemoteShutter_WatchMessage.add(state: state, &fbb)
    return RemoteShutter_WatchMessage.endWatchMessage(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.type.p, fieldName: "type", required: false, type: RemoteShutter_WatchMessageType.self)
    try _v.visit(field: VTOFFSET.command.p, fieldName: "command", required: false, type: ForwardOffset<RemoteShutter_WatchCommand>.self)
    try _v.visit(field: VTOFFSET.state.p, fieldName: "state", required: false, type: ForwardOffset<RemoteShutter_WatchCameraState>.self)
    _v.finish()
  }
}

