// automatically generated by the FlatBuffers compiler, do not modify
// swiftlint:disable all
// swiftformat:disable all

import FlatBuffers

public enum RemoteShutter_CommandAction: Int8, Enum, Verifiable {
  public typealias T = Int8
  public static var byteSize: Int { return MemoryLayout<Int8>.size }
  public var value: Int8 { return self.rawValue }
  case takepicture = 0
  case toggletorch = 1
  case toggleflash = 2
  case togglecamera = 3
  case setzoom = 4
  case switchlens = 5
  case startrecording = 6
  case stoprecording = 7
  case requestcapabilities = 8
  case settorchmode = 9
  case setflashmode = 10
  case requestframe = 11
  case peerbecamecamera = 12
  case peerbecamemonitor = 13

  public static var max: RemoteShutter_CommandAction { return .peerbecamemonitor }
  public static var min: RemoteShutter_CommandAction { return .takepicture }
}


public enum RemoteShutter_CameraPosition: Int8, Enum, Verifiable {
  public typealias T = Int8
  public static var byteSize: Int { return MemoryLayout<Int8>.size }
  public var value: Int8 { return self.rawValue }
  case back = 0
  case front = 1

  public static var max: RemoteShutter_CameraPosition { return .front }
  public static var min: RemoteShutter_CameraPosition { return .back }
}


public enum RemoteShutter_TorchMode: Int8, Enum, Verifiable {
  public typealias T = Int8
  public static var byteSize: Int { return MemoryLayout<Int8>.size }
  public var value: Int8 { return self.rawValue }
  case off = 0
  case on = 1
  case auto = 2

  public static var max: RemoteShutter_TorchMode { return .auto }
  public static var min: RemoteShutter_TorchMode { return .off }
}


public enum RemoteShutter_FlashMode: Int8, Enum, Verifiable {
  public typealias T = Int8
  public static var byteSize: Int { return MemoryLayout<Int8>.size }
  public var value: Int8 { return self.rawValue }
  case off = 0
  case on = 1
  case auto = 2

  public static var max: RemoteShutter_FlashMode { return .auto }
  public static var min: RemoteShutter_FlashMode { return .off }
}


public enum RemoteShutter_CameraLensType: Int8, Enum, Verifiable {
  public typealias T = Int8
  public static var byteSize: Int { return MemoryLayout<Int8>.size }
  public var value: Int8 { return self.rawValue }
  case wideangle = 0
  case ultrawide = 1
  case telephoto = 2
  case dualcamera = 3

  public static var max: RemoteShutter_CameraLensType { return .dualcamera }
  public static var min: RemoteShutter_CameraLensType { return .wideangle }
}


public enum RemoteShutter_ConnectionStatus: Int8, Enum, Verifiable {
  public typealias T = Int8
  public static var byteSize: Int { return MemoryLayout<Int8>.size }
  public var value: Int8 { return self.rawValue }
  case disconnected = 0
  case connecting = 1
  case connected = 2
  case scanning = 3
  case error = 4

  public static var max: RemoteShutter_ConnectionStatus { return .error }
  public static var min: RemoteShutter_ConnectionStatus { return .disconnected }
}


public enum RemoteShutter_MessageType: Int8, Enum, Verifiable {
  public typealias T = Int8
  public static var byteSize: Int { return MemoryLayout<Int8>.size }
  public var value: Int8 { return self.rawValue }
  case cameracommand = 0
  case camerastateresponse = 1
  case framedata = 2
  case mediadata = 3
  case heartbeat = 4
  case error = 5

  public static var max: RemoteShutter_MessageType { return .error }
  public static var min: RemoteShutter_MessageType { return .cameracommand }
}


public enum RemoteShutter_MediaType: Int8, Enum, Verifiable {
  public typealias T = Int8
  public static var byteSize: Int { return MemoryLayout<Int8>.size }
  public var value: Int8 { return self.rawValue }
  case photo = 0
  case video = 1

  public static var max: RemoteShutter_MediaType { return .video }
  public static var min: RemoteShutter_MediaType { return .photo }
}


public struct RemoteShutter_CommandParameters: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_25_2_10() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  public static var id: String { "RCAM" } 
  public static func finish(_ fbb: inout FlatBufferBuilder, end: Offset, prefix: Bool = false) { fbb.finish(offset: end, fileId: RemoteShutter_CommandParameters.id, addPrefix: prefix) }
  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case sendToRemote = 4
    case zoomFactor = 6
    case lensType = 8
    case torchMode = 10
    case flashMode = 12
    case bundleVersion = 14
    case shortVersion = 16
    case platform = 18
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var sendToRemote: Bool { let o = _accessor.offset(VTOFFSET.sendToRemote.v); return o == 0 ? false : _accessor.readBuffer(of: Bool.self, at: o) }
  public var zoomFactor: Double { let o = _accessor.offset(VTOFFSET.zoomFactor.v); return o == 0 ? 0.0 : _accessor.readBuffer(of: Double.self, at: o) }
  public var lensType: RemoteShutter_CameraLensType { let o = _accessor.offset(VTOFFSET.lensType.v); return o == 0 ? .wideangle : RemoteShutter_CameraLensType(rawValue: _accessor.readBuffer(of: Int8.self, at: o)) ?? .wideangle }
  public var torchMode: RemoteShutter_TorchMode { let o = _accessor.offset(VTOFFSET.torchMode.v); return o == 0 ? .off : RemoteShutter_TorchMode(rawValue: _accessor.readBuffer(of: Int8.self, at: o)) ?? .off }
  public var flashMode: RemoteShutter_FlashMode { let o = _accessor.offset(VTOFFSET.flashMode.v); return o == 0 ? .off : RemoteShutter_FlashMode(rawValue: _accessor.readBuffer(of: Int8.self, at: o)) ?? .off }
  public var bundleVersion: Int32 { let o = _accessor.offset(VTOFFSET.bundleVersion.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int32.self, at: o) }
  public var shortVersion: String? { let o = _accessor.offset(VTOFFSET.shortVersion.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var shortVersionSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.shortVersion.v) }
  public var platform: String? { let o = _accessor.offset(VTOFFSET.platform.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var platformSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.platform.v) }
  public static func startCommandParameters(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 8) }
  public static func add(sendToRemote: Bool, _ fbb: inout FlatBufferBuilder) { fbb.add(element: sendToRemote, def: false,
   at: VTOFFSET.sendToRemote.p) }
  public static func add(zoomFactor: Double, _ fbb: inout FlatBufferBuilder) { fbb.add(element: zoomFactor, def: 0.0, at: VTOFFSET.zoomFactor.p) }
  public static func add(lensType: RemoteShutter_CameraLensType, _ fbb: inout FlatBufferBuilder) { fbb.add(element: lensType.rawValue, def: 0, at: VTOFFSET.lensType.p) }
  public static func add(torchMode: RemoteShutter_TorchMode, _ fbb: inout FlatBufferBuilder) { fbb.add(element: torchMode.rawValue, def: 0, at: VTOFFSET.torchMode.p) }
  public static func add(flashMode: RemoteShutter_FlashMode, _ fbb: inout FlatBufferBuilder) { fbb.add(element: flashMode.rawValue, def: 0, at: VTOFFSET.flashMode.p) }
  public static func add(bundleVersion: Int32, _ fbb: inout FlatBufferBuilder) { fbb.add(element: bundleVersion, def: 0, at: VTOFFSET.bundleVersion.p) }
  public static func add(shortVersion: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: shortVersion, at: VTOFFSET.shortVersion.p) }
  public static func add(platform: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: platform, at: VTOFFSET.platform.p) }
  public static func endCommandParameters(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createCommandParameters(
    _ fbb: inout FlatBufferBuilder,
    sendToRemote: Bool = false,
    zoomFactor: Double = 0.0,
    lensType: RemoteShutter_CameraLensType = .wideangle,
    torchMode: RemoteShutter_TorchMode = .off,
    flashMode: RemoteShutter_FlashMode = .off,
    bundleVersion: Int32 = 0,
    shortVersionOffset shortVersion: Offset = Offset(),
    platformOffset platform: Offset = Offset()
  ) -> Offset {
    let __start = RemoteShutter_CommandParameters.startCommandParameters(&fbb)
    RemoteShutter_CommandParameters.add(sendToRemote: sendToRemote, &fbb)
    RemoteShutter_CommandParameters.add(zoomFactor: zoomFactor, &fbb)
    RemoteShutter_CommandParameters.add(lensType: lensType, &fbb)
    RemoteShutter_CommandParameters.add(torchMode: torchMode, &fbb)
    RemoteShutter_CommandParameters.add(flashMode: flashMode, &fbb)
    RemoteShutter_CommandParameters.add(bundleVersion: bundleVersion, &fbb)
    RemoteShutter_CommandParameters.add(shortVersion: shortVersion, &fbb)
    RemoteShutter_CommandParameters.add(platform: platform, &fbb)
    return RemoteShutter_CommandParameters.endCommandParameters(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.sendToRemote.p, fieldName: "sendToRemote", required: false, type: Bool.self)
    try _v.visit(field: VTOFFSET.zoomFactor.p, fieldName: "zoomFactor", required: false, type: Double.self)
    try _v.visit(field: VTOFFSET.lensType.p, fieldName: "lensType", required: false, type: RemoteShutter_CameraLensType.self)
    try _v.visit(field: VTOFFSET.torchMode.p, fieldName: "torchMode", required: false, type: RemoteShutter_TorchMode.self)
    try _v.visit(field: VTOFFSET.flashMode.p, fieldName: "flashMode", required: false, type: RemoteShutter_FlashMode.self)
    try _v.visit(field: VTOFFSET.bundleVersion.p, fieldName: "bundleVersion", required: false, type: Int32.self)
    try _v.visit(field: VTOFFSET.shortVersion.p, fieldName: "shortVersion", required: false, type: ForwardOffset<String>.self)
    try _v.visit(field: VTOFFSET.platform.p, fieldName: "platform", required: false, type: ForwardOffset<String>.self)
    _v.finish()
  }
}

public struct RemoteShutter_CameraCommand: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_25_2_10() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  public static var id: String { "RCAM" } 
  public static func finish(_ fbb: inout FlatBufferBuilder, end: Offset, prefix: Bool = false) { fbb.finish(offset: end, fileId: RemoteShutter_CameraCommand.id, addPrefix: prefix) }
  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case id = 4
    case timestamp = 6
    case action = 8
    case parameters = 10
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var id: String? { let o = _accessor.offset(VTOFFSET.id.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var idSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.id.v) }
  public var timestamp: UInt64 { let o = _accessor.offset(VTOFFSET.timestamp.v); return o == 0 ? 0 : _accessor.readBuffer(of: UInt64.self, at: o) }
  public var action: RemoteShutter_CommandAction { let o = _accessor.offset(VTOFFSET.action.v); return o == 0 ? .takepicture : RemoteShutter_CommandAction(rawValue: _accessor.readBuffer(of: Int8.self, at: o)) ?? .takepicture }
  public var parameters: RemoteShutter_CommandParameters? { let o = _accessor.offset(VTOFFSET.parameters.v); return o == 0 ? nil : RemoteShutter_CommandParameters(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public static func startCameraCommand(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 4) }
  public static func add(id: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: id, at: VTOFFSET.id.p) }
  public static func add(timestamp: UInt64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: timestamp, def: 0, at: VTOFFSET.timestamp.p) }
  public static func add(action: RemoteShutter_CommandAction, _ fbb: inout FlatBufferBuilder) { fbb.add(element: action.rawValue, def: 0, at: VTOFFSET.action.p) }
  public static func add(parameters: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: parameters, at: VTOFFSET.parameters.p) }
  public static func endCameraCommand(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createCameraCommand(
    _ fbb: inout FlatBufferBuilder,
    idOffset id: Offset = Offset(),
    timestamp: UInt64 = 0,
    action: RemoteShutter_CommandAction = .takepicture,
    parametersOffset parameters: Offset = Offset()
  ) -> Offset {
    let __start = RemoteShutter_CameraCommand.startCameraCommand(&fbb)
    RemoteShutter_CameraCommand.add(id: id, &fbb)
    RemoteShutter_CameraCommand.add(timestamp: timestamp, &fbb)
    RemoteShutter_CameraCommand.add(action: action, &fbb)
    RemoteShutter_CameraCommand.add(parameters: parameters, &fbb)
    return RemoteShutter_CameraCommand.endCameraCommand(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.id.p, fieldName: "id", required: false, type: ForwardOffset<String>.self)
    try _v.visit(field: VTOFFSET.timestamp.p, fieldName: "timestamp", required: false, type: UInt64.self)
    try _v.visit(field: VTOFFSET.action.p, fieldName: "action", required: false, type: RemoteShutter_CommandAction.self)
    try _v.visit(field: VTOFFSET.parameters.p, fieldName: "parameters", required: false, type: ForwardOffset<RemoteShutter_CommandParameters>.self)
    _v.finish()
  }
}

public struct RemoteShutter_ZoomRange: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_25_2_10() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  public static var id: String { "RCAM" } 
  public static func finish(_ fbb: inout FlatBufferBuilder, end: Offset, prefix: Bool = false) { fbb.finish(offset: end, fileId: RemoteShutter_ZoomRange.id, addPrefix: prefix) }
  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case minZoom = 4
    case maxZoom = 6
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var minZoom: Double { let o = _accessor.offset(VTOFFSET.minZoom.v); return o == 0 ? 0.0 : _accessor.readBuffer(of: Double.self, at: o) }
  public var maxZoom: Double { let o = _accessor.offset(VTOFFSET.maxZoom.v); return o == 0 ? 0.0 : _accessor.readBuffer(of: Double.self, at: o) }
  public static func startZoomRange(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 2) }
  public static func add(minZoom: Double, _ fbb: inout FlatBufferBuilder) { fbb.add(element: minZoom, def: 0.0, at: VTOFFSET.minZoom.p) }
  public static func add(maxZoom: Double, _ fbb: inout FlatBufferBuilder) { fbb.add(element: maxZoom, def: 0.0, at: VTOFFSET.maxZoom.p) }
  public static func endZoomRange(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createZoomRange(
    _ fbb: inout FlatBufferBuilder,
    minZoom: Double = 0.0,
    maxZoom: Double = 0.0
  ) -> Offset {
    let __start = RemoteShutter_ZoomRange.startZoomRange(&fbb)
    RemoteShutter_ZoomRange.add(minZoom: minZoom, &fbb)
    RemoteShutter_ZoomRange.add(maxZoom: maxZoom, &fbb)
    return RemoteShutter_ZoomRange.endZoomRange(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.minZoom.p, fieldName: "minZoom", required: false, type: Double.self)
    try _v.visit(field: VTOFFSET.maxZoom.p, fieldName: "maxZoom", required: false, type: Double.self)
    _v.finish()
  }
}

public struct RemoteShutter_CameraLimits: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_25_2_10() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  public static var id: String { "RCAM" } 
  public static func finish(_ fbb: inout FlatBufferBuilder, end: Offset, prefix: Bool = false) { fbb.finish(offset: end, fileId: RemoteShutter_CameraLimits.id, addPrefix: prefix) }
  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case zoomRange = 4
    case availableLenses = 6
    case supportsFlash = 8
    case supportsTorch = 10
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var zoomRange: RemoteShutter_ZoomRange? { let o = _accessor.offset(VTOFFSET.zoomRange.v); return o == 0 ? nil : RemoteShutter_ZoomRange(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public var hasAvailableLenses: Bool { let o = _accessor.offset(VTOFFSET.availableLenses.v); return o == 0 ? false : true }
  public var availableLensesCount: Int32 { let o = _accessor.offset(VTOFFSET.availableLenses.v); return o == 0 ? 0 : _accessor.vector(count: o) }
  public func availableLenses(at index: Int32) -> RemoteShutter_CameraLensType? { let o = _accessor.offset(VTOFFSET.availableLenses.v); return o == 0 ? RemoteShutter_CameraLensType.wideangle : RemoteShutter_CameraLensType(rawValue: _accessor.directRead(of: Int8.self, offset: _accessor.vector(at: o) + index * 1)) }
  public var supportsFlash: Bool { let o = _accessor.offset(VTOFFSET.supportsFlash.v); return o == 0 ? false : _accessor.readBuffer(of: Bool.self, at: o) }
  public var supportsTorch: Bool { let o = _accessor.offset(VTOFFSET.supportsTorch.v); return o == 0 ? false : _accessor.readBuffer(of: Bool.self, at: o) }
  public static func startCameraLimits(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 4) }
  public static func add(zoomRange: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: zoomRange, at: VTOFFSET.zoomRange.p) }
  public static func addVectorOf(availableLenses: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: availableLenses, at: VTOFFSET.availableLenses.p) }
  public static func add(supportsFlash: Bool, _ fbb: inout FlatBufferBuilder) { fbb.add(element: supportsFlash, def: false,
   at: VTOFFSET.supportsFlash.p) }
  public static func add(supportsTorch: Bool, _ fbb: inout FlatBufferBuilder) { fbb.add(element: supportsTorch, def: false,
   at: VTOFFSET.supportsTorch.p) }
  public static func endCameraLimits(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createCameraLimits(
    _ fbb: inout FlatBufferBuilder,
    zoomRangeOffset zoomRange: Offset = Offset(),
    availableLensesVectorOffset availableLenses: Offset = Offset(),
    supportsFlash: Bool = false,
    supportsTorch: Bool = false
  ) -> Offset {
    let __start = RemoteShutter_CameraLimits.startCameraLimits(&fbb)
    RemoteShutter_CameraLimits.add(zoomRange: zoomRange, &fbb)
    RemoteShutter_CameraLimits.addVectorOf(availableLenses: availableLenses, &fbb)
    RemoteShutter_CameraLimits.add(supportsFlash: supportsFlash, &fbb)
    RemoteShutter_CameraLimits.add(supportsTorch: supportsTorch, &fbb)
    return RemoteShutter_CameraLimits.endCameraLimits(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.zoomRange.p, fieldName: "zoomRange", required: false, type: ForwardOffset<RemoteShutter_ZoomRange>.self)
    try _v.visit(field: VTOFFSET.availableLenses.p, fieldName: "availableLenses", required: false, type: ForwardOffset<Vector<RemoteShutter_CameraLensType, RemoteShutter_CameraLensType>>.self)
    try _v.visit(field: VTOFFSET.supportsFlash.p, fieldName: "supportsFlash", required: false, type: Bool.self)
    try _v.visit(field: VTOFFSET.supportsTorch.p, fieldName: "supportsTorch", required: false, type: Bool.self)
    _v.finish()
  }
}

public struct RemoteShutter_CameraInfo: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_25_2_10() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  public static var id: String { "RCAM" } 
  public static func finish(_ fbb: inout FlatBufferBuilder, end: Offset, prefix: Bool = false) { fbb.finish(offset: end, fileId: RemoteShutter_CameraInfo.id, addPrefix: prefix) }
  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case availableLenses = 4
    case hasFlash = 6
    case hasTorch = 8
    case zoomCapabilities = 10
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var hasAvailableLenses: Bool { let o = _accessor.offset(VTOFFSET.availableLenses.v); return o == 0 ? false : true }
  public var availableLensesCount: Int32 { let o = _accessor.offset(VTOFFSET.availableLenses.v); return o == 0 ? 0 : _accessor.vector(count: o) }
  public func availableLenses(at index: Int32) -> RemoteShutter_CameraLensType? { let o = _accessor.offset(VTOFFSET.availableLenses.v); return o == 0 ? RemoteShutter_CameraLensType.wideangle : RemoteShutter_CameraLensType(rawValue: _accessor.directRead(of: Int8.self, offset: _accessor.vector(at: o) + index * 1)) }
  public var hasFlash: Bool { let o = _accessor.offset(VTOFFSET.hasFlash.v); return o == 0 ? false : _accessor.readBuffer(of: Bool.self, at: o) }
  public var hasTorch: Bool { let o = _accessor.offset(VTOFFSET.hasTorch.v); return o == 0 ? false : _accessor.readBuffer(of: Bool.self, at: o) }
  public var hasZoomCapabilities: Bool { let o = _accessor.offset(VTOFFSET.zoomCapabilities.v); return o == 0 ? false : true }
  public var zoomCapabilitiesCount: Int32 { let o = _accessor.offset(VTOFFSET.zoomCapabilities.v); return o == 0 ? 0 : _accessor.vector(count: o) }
  public func zoomCapabilities(at index: Int32) -> RemoteShutter_ZoomCapability? { let o = _accessor.offset(VTOFFSET.zoomCapabilities.v); return o == 0 ? nil : RemoteShutter_ZoomCapability(_accessor.bb, o: _accessor.indirect(_accessor.vector(at: o) + index * 4)) }
  public static func startCameraInfo(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 4) }
  public static func addVectorOf(availableLenses: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: availableLenses, at: VTOFFSET.availableLenses.p) }
  public static func add(hasFlash: Bool, _ fbb: inout FlatBufferBuilder) { fbb.add(element: hasFlash, def: false,
   at: VTOFFSET.hasFlash.p) }
  public static func add(hasTorch: Bool, _ fbb: inout FlatBufferBuilder) { fbb.add(element: hasTorch, def: false,
   at: VTOFFSET.hasTorch.p) }
  public static func addVectorOf(zoomCapabilities: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: zoomCapabilities, at: VTOFFSET.zoomCapabilities.p) }
  public static func endCameraInfo(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createCameraInfo(
    _ fbb: inout FlatBufferBuilder,
    availableLensesVectorOffset availableLenses: Offset = Offset(),
    hasFlash: Bool = false,
    hasTorch: Bool = false,
    zoomCapabilitiesVectorOffset zoomCapabilities: Offset = Offset()
  ) -> Offset {
    let __start = RemoteShutter_CameraInfo.startCameraInfo(&fbb)
    RemoteShutter_CameraInfo.addVectorOf(availableLenses: availableLenses, &fbb)
    RemoteShutter_CameraInfo.add(hasFlash: hasFlash, &fbb)
    RemoteShutter_CameraInfo.add(hasTorch: hasTorch, &fbb)
    RemoteShutter_CameraInfo.addVectorOf(zoomCapabilities: zoomCapabilities, &fbb)
    return RemoteShutter_CameraInfo.endCameraInfo(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.availableLenses.p, fieldName: "availableLenses", required: false, type: ForwardOffset<Vector<RemoteShutter_CameraLensType, RemoteShutter_CameraLensType>>.self)
    try _v.visit(field: VTOFFSET.hasFlash.p, fieldName: "hasFlash", required: false, type: Bool.self)
    try _v.visit(field: VTOFFSET.hasTorch.p, fieldName: "hasTorch", required: false, type: Bool.self)
    try _v.visit(field: VTOFFSET.zoomCapabilities.p, fieldName: "zoomCapabilities", required: false, type: ForwardOffset<Vector<ForwardOffset<RemoteShutter_ZoomCapability>, RemoteShutter_ZoomCapability>>.self)
    _v.finish()
  }
}

public struct RemoteShutter_ZoomCapability: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_25_2_10() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  public static var id: String { "RCAM" } 
  public static func finish(_ fbb: inout FlatBufferBuilder, end: Offset, prefix: Bool = false) { fbb.finish(offset: end, fileId: RemoteShutter_ZoomCapability.id, addPrefix: prefix) }
  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case lensType = 4
    case zoomRange = 6
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var lensType: RemoteShutter_CameraLensType { let o = _accessor.offset(VTOFFSET.lensType.v); return o == 0 ? .wideangle : RemoteShutter_CameraLensType(rawValue: _accessor.readBuffer(of: Int8.self, at: o)) ?? .wideangle }
  public var zoomRange: RemoteShutter_ZoomRange? { let o = _accessor.offset(VTOFFSET.zoomRange.v); return o == 0 ? nil : RemoteShutter_ZoomRange(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public static func startZoomCapability(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 2) }
  public static func add(lensType: RemoteShutter_CameraLensType, _ fbb: inout FlatBufferBuilder) { fbb.add(element: lensType.rawValue, def: 0, at: VTOFFSET.lensType.p) }
  public static func add(zoomRange: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: zoomRange, at: VTOFFSET.zoomRange.p) }
  public static func endZoomCapability(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createZoomCapability(
    _ fbb: inout FlatBufferBuilder,
    lensType: RemoteShutter_CameraLensType = .wideangle,
    zoomRangeOffset zoomRange: Offset = Offset()
  ) -> Offset {
    let __start = RemoteShutter_ZoomCapability.startZoomCapability(&fbb)
    RemoteShutter_ZoomCapability.add(lensType: lensType, &fbb)
    RemoteShutter_ZoomCapability.add(zoomRange: zoomRange, &fbb)
    return RemoteShutter_ZoomCapability.endZoomCapability(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.lensType.p, fieldName: "lensType", required: false, type: RemoteShutter_CameraLensType.self)
    try _v.visit(field: VTOFFSET.zoomRange.p, fieldName: "zoomRange", required: false, type: ForwardOffset<RemoteShutter_ZoomRange>.self)
    _v.finish()
  }
}

public struct RemoteShutter_CameraState: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_25_2_10() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  public static var id: String { "RCAM" } 
  public static func finish(_ fbb: inout FlatBufferBuilder, end: Offset, prefix: Bool = false) { fbb.finish(offset: end, fileId: RemoteShutter_CameraState.id, addPrefix: prefix) }
  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case currentCamera = 4
    case currentLens = 6
    case zoomFactor = 8
    case torchMode = 10
    case flashMode = 12
    case isRecording = 14
    case connectionStatus = 16
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var currentCamera: RemoteShutter_CameraPosition { let o = _accessor.offset(VTOFFSET.currentCamera.v); return o == 0 ? .back : RemoteShutter_CameraPosition(rawValue: _accessor.readBuffer(of: Int8.self, at: o)) ?? .back }
  public var currentLens: RemoteShutter_CameraLensType { let o = _accessor.offset(VTOFFSET.currentLens.v); return o == 0 ? .wideangle : RemoteShutter_CameraLensType(rawValue: _accessor.readBuffer(of: Int8.self, at: o)) ?? .wideangle }
  public var zoomFactor: Double { let o = _accessor.offset(VTOFFSET.zoomFactor.v); return o == 0 ? 0.0 : _accessor.readBuffer(of: Double.self, at: o) }
  public var torchMode: RemoteShutter_TorchMode { let o = _accessor.offset(VTOFFSET.torchMode.v); return o == 0 ? .off : RemoteShutter_TorchMode(rawValue: _accessor.readBuffer(of: Int8.self, at: o)) ?? .off }
  public var flashMode: RemoteShutter_FlashMode { let o = _accessor.offset(VTOFFSET.flashMode.v); return o == 0 ? .off : RemoteShutter_FlashMode(rawValue: _accessor.readBuffer(of: Int8.self, at: o)) ?? .off }
  public var isRecording: Bool { let o = _accessor.offset(VTOFFSET.isRecording.v); return o == 0 ? false : _accessor.readBuffer(of: Bool.self, at: o) }
  public var connectionStatus: RemoteShutter_ConnectionStatus { let o = _accessor.offset(VTOFFSET.connectionStatus.v); return o == 0 ? .disconnected : RemoteShutter_ConnectionStatus(rawValue: _accessor.readBuffer(of: Int8.self, at: o)) ?? .disconnected }
  public static func startCameraState(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 7) }
  public static func add(currentCamera: RemoteShutter_CameraPosition, _ fbb: inout FlatBufferBuilder) { fbb.add(element: currentCamera.rawValue, def: 0, at: VTOFFSET.currentCamera.p) }
  public static func add(currentLens: RemoteShutter_CameraLensType, _ fbb: inout FlatBufferBuilder) { fbb.add(element: currentLens.rawValue, def: 0, at: VTOFFSET.currentLens.p) }
  public static func add(zoomFactor: Double, _ fbb: inout FlatBufferBuilder) { fbb.add(element: zoomFactor, def: 0.0, at: VTOFFSET.zoomFactor.p) }
  public static func add(torchMode: RemoteShutter_TorchMode, _ fbb: inout FlatBufferBuilder) { fbb.add(element: torchMode.rawValue, def: 0, at: VTOFFSET.torchMode.p) }
  public static func add(flashMode: RemoteShutter_FlashMode, _ fbb: inout FlatBufferBuilder) { fbb.add(element: flashMode.rawValue, def: 0, at: VTOFFSET.flashMode.p) }
  public static func add(isRecording: Bool, _ fbb: inout FlatBufferBuilder) { fbb.add(element: isRecording, def: false,
   at: VTOFFSET.isRecording.p) }
  public static func add(connectionStatus: RemoteShutter_ConnectionStatus, _ fbb: inout FlatBufferBuilder) { fbb.add(element: connectionStatus.rawValue, def: 0, at: VTOFFSET.connectionStatus.p) }
  public static func endCameraState(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createCameraState(
    _ fbb: inout FlatBufferBuilder,
    currentCamera: RemoteShutter_CameraPosition = .back,
    currentLens: RemoteShutter_CameraLensType = .wideangle,
    zoomFactor: Double = 0.0,
    torchMode: RemoteShutter_TorchMode = .off,
    flashMode: RemoteShutter_FlashMode = .off,
    isRecording: Bool = false,
    connectionStatus: RemoteShutter_ConnectionStatus = .disconnected
  ) -> Offset {
    let __start = RemoteShutter_CameraState.startCameraState(&fbb)
    RemoteShutter_CameraState.add(currentCamera: currentCamera, &fbb)
    RemoteShutter_CameraState.add(currentLens: currentLens, &fbb)
    RemoteShutter_CameraState.add(zoomFactor: zoomFactor, &fbb)
    RemoteShutter_CameraState.add(torchMode: torchMode, &fbb)
    RemoteShutter_CameraState.add(flashMode: flashMode, &fbb)
    RemoteShutter_CameraState.add(isRecording: isRecording, &fbb)
    RemoteShutter_CameraState.add(connectionStatus: connectionStatus, &fbb)
    return RemoteShutter_CameraState.endCameraState(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.currentCamera.p, fieldName: "currentCamera", required: false, type: RemoteShutter_CameraPosition.self)
    try _v.visit(field: VTOFFSET.currentLens.p, fieldName: "currentLens", required: false, type: RemoteShutter_CameraLensType.self)
    try _v.visit(field: VTOFFSET.zoomFactor.p, fieldName: "zoomFactor", required: false, type: Double.self)
    try _v.visit(field: VTOFFSET.torchMode.p, fieldName: "torchMode", required: false, type: RemoteShutter_TorchMode.self)
    try _v.visit(field: VTOFFSET.flashMode.p, fieldName: "flashMode", required: false, type: RemoteShutter_FlashMode.self)
    try _v.visit(field: VTOFFSET.isRecording.p, fieldName: "isRecording", required: false, type: Bool.self)
    try _v.visit(field: VTOFFSET.connectionStatus.p, fieldName: "connectionStatus", required: false, type: RemoteShutter_ConnectionStatus.self)
    _v.finish()
  }
}

public struct RemoteShutter_CameraCapabilities: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_25_2_10() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  public static var id: String { "RCAM" } 
  public static func finish(_ fbb: inout FlatBufferBuilder, end: Offset, prefix: Bool = false) { fbb.finish(offset: end, fileId: RemoteShutter_CameraCapabilities.id, addPrefix: prefix) }
  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case frontCamera = 4
    case backCamera = 6
    case availableActions = 8
    case currentLimits = 10
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var frontCamera: RemoteShutter_CameraInfo? { let o = _accessor.offset(VTOFFSET.frontCamera.v); return o == 0 ? nil : RemoteShutter_CameraInfo(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public var backCamera: RemoteShutter_CameraInfo? { let o = _accessor.offset(VTOFFSET.backCamera.v); return o == 0 ? nil : RemoteShutter_CameraInfo(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public var hasAvailableActions: Bool { let o = _accessor.offset(VTOFFSET.availableActions.v); return o == 0 ? false : true }
  public var availableActionsCount: Int32 { let o = _accessor.offset(VTOFFSET.availableActions.v); return o == 0 ? 0 : _accessor.vector(count: o) }
  public func availableActions(at index: Int32) -> RemoteShutter_CommandAction? { let o = _accessor.offset(VTOFFSET.availableActions.v); return o == 0 ? RemoteShutter_CommandAction.takepicture : RemoteShutter_CommandAction(rawValue: _accessor.directRead(of: Int8.self, offset: _accessor.vector(at: o) + index * 1)) }
  public var currentLimits: RemoteShutter_CameraLimits? { let o = _accessor.offset(VTOFFSET.currentLimits.v); return o == 0 ? nil : RemoteShutter_CameraLimits(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public static func startCameraCapabilities(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 4) }
  public static func add(frontCamera: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: frontCamera, at: VTOFFSET.frontCamera.p) }
  public static func add(backCamera: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: backCamera, at: VTOFFSET.backCamera.p) }
  public static func addVectorOf(availableActions: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: availableActions, at: VTOFFSET.availableActions.p) }
  public static func add(currentLimits: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: currentLimits, at: VTOFFSET.currentLimits.p) }
  public static func endCameraCapabilities(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createCameraCapabilities(
    _ fbb: inout FlatBufferBuilder,
    frontCameraOffset frontCamera: Offset = Offset(),
    backCameraOffset backCamera: Offset = Offset(),
    availableActionsVectorOffset availableActions: Offset = Offset(),
    currentLimitsOffset currentLimits: Offset = Offset()
  ) -> Offset {
    let __start = RemoteShutter_CameraCapabilities.startCameraCapabilities(&fbb)
    RemoteShutter_CameraCapabilities.add(frontCamera: frontCamera, &fbb)
    RemoteShutter_CameraCapabilities.add(backCamera: backCamera, &fbb)
    RemoteShutter_CameraCapabilities.addVectorOf(availableActions: availableActions, &fbb)
    RemoteShutter_CameraCapabilities.add(currentLimits: currentLimits, &fbb)
    return RemoteShutter_CameraCapabilities.endCameraCapabilities(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.frontCamera.p, fieldName: "frontCamera", required: false, type: ForwardOffset<RemoteShutter_CameraInfo>.self)
    try _v.visit(field: VTOFFSET.backCamera.p, fieldName: "backCamera", required: false, type: ForwardOffset<RemoteShutter_CameraInfo>.self)
    try _v.visit(field: VTOFFSET.availableActions.p, fieldName: "availableActions", required: false, type: ForwardOffset<Vector<RemoteShutter_CommandAction, RemoteShutter_CommandAction>>.self)
    try _v.visit(field: VTOFFSET.currentLimits.p, fieldName: "currentLimits", required: false, type: ForwardOffset<RemoteShutter_CameraLimits>.self)
    _v.finish()
  }
}

public struct RemoteShutter_CameraStateResponse: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_25_2_10() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  public static var id: String { "RCAM" } 
  public static func finish(_ fbb: inout FlatBufferBuilder, end: Offset, prefix: Bool = false) { fbb.finish(offset: end, fileId: RemoteShutter_CameraStateResponse.id, addPrefix: prefix) }
  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case commandId = 4
    case timestamp = 6
    case success = 8
    case error = 10
    case currentState = 12
    case capabilities = 14
    case mediaData = 16
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var commandId: String? { let o = _accessor.offset(VTOFFSET.commandId.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var commandIdSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.commandId.v) }
  public var timestamp: UInt64 { let o = _accessor.offset(VTOFFSET.timestamp.v); return o == 0 ? 0 : _accessor.readBuffer(of: UInt64.self, at: o) }
  public var success: Bool { let o = _accessor.offset(VTOFFSET.success.v); return o == 0 ? false : _accessor.readBuffer(of: Bool.self, at: o) }
  public var error: String? { let o = _accessor.offset(VTOFFSET.error.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var errorSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.error.v) }
  public var currentState: RemoteShutter_CameraState? { let o = _accessor.offset(VTOFFSET.currentState.v); return o == 0 ? nil : RemoteShutter_CameraState(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public var capabilities: RemoteShutter_CameraCapabilities? { let o = _accessor.offset(VTOFFSET.capabilities.v); return o == 0 ? nil : RemoteShutter_CameraCapabilities(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public var mediaData: RemoteShutter_MediaData? { let o = _accessor.offset(VTOFFSET.mediaData.v); return o == 0 ? nil : RemoteShutter_MediaData(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public static func startCameraStateResponse(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 7) }
  public static func add(commandId: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: commandId, at: VTOFFSET.commandId.p) }
  public static func add(timestamp: UInt64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: timestamp, def: 0, at: VTOFFSET.timestamp.p) }
  public static func add(success: Bool, _ fbb: inout FlatBufferBuilder) { fbb.add(element: success, def: false,
   at: VTOFFSET.success.p) }
  public static func add(error: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: error, at: VTOFFSET.error.p) }
  public static func add(currentState: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: currentState, at: VTOFFSET.currentState.p) }
  public static func add(capabilities: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: capabilities, at: VTOFFSET.capabilities.p) }
  public static func add(mediaData: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: mediaData, at: VTOFFSET.mediaData.p) }
  public static func endCameraStateResponse(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createCameraStateResponse(
    _ fbb: inout FlatBufferBuilder,
    commandIdOffset commandId: Offset = Offset(),
    timestamp: UInt64 = 0,
    success: Bool = false,
    errorOffset error: Offset = Offset(),
    currentStateOffset currentState: Offset = Offset(),
    capabilitiesOffset capabilities: Offset = Offset(),
    mediaDataOffset mediaData: Offset = Offset()
  ) -> Offset {
    let __start = RemoteShutter_CameraStateResponse.startCameraStateResponse(&fbb)
    RemoteShutter_CameraStateResponse.add(commandId: commandId, &fbb)
    RemoteShutter_CameraStateResponse.add(timestamp: timestamp, &fbb)
    RemoteShutter_CameraStateResponse.add(success: success, &fbb)
    RemoteShutter_CameraStateResponse.add(error: error, &fbb)
    RemoteShutter_CameraStateResponse.add(currentState: currentState, &fbb)
    RemoteShutter_CameraStateResponse.add(capabilities: capabilities, &fbb)
    RemoteShutter_CameraStateResponse.add(mediaData: mediaData, &fbb)
    return RemoteShutter_CameraStateResponse.endCameraStateResponse(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.commandId.p, fieldName: "commandId", required: false, type: ForwardOffset<String>.self)
    try _v.visit(field: VTOFFSET.timestamp.p, fieldName: "timestamp", required: false, type: UInt64.self)
    try _v.visit(field: VTOFFSET.success.p, fieldName: "success", required: false, type: Bool.self)
    try _v.visit(field: VTOFFSET.error.p, fieldName: "error", required: false, type: ForwardOffset<String>.self)
    try _v.visit(field: VTOFFSET.currentState.p, fieldName: "currentState", required: false, type: ForwardOffset<RemoteShutter_CameraState>.self)
    try _v.visit(field: VTOFFSET.capabilities.p, fieldName: "capabilities", required: false, type: ForwardOffset<RemoteShutter_CameraCapabilities>.self)
    try _v.visit(field: VTOFFSET.mediaData.p, fieldName: "mediaData", required: false, type: ForwardOffset<RemoteShutter_MediaData>.self)
    _v.finish()
  }
}

public struct RemoteShutter_FrameData: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_25_2_10() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  public static var id: String { "RCAM" } 
  public static func finish(_ fbb: inout FlatBufferBuilder, end: Offset, prefix: Bool = false) { fbb.finish(offset: end, fileId: RemoteShutter_FrameData.id, addPrefix: prefix) }
  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case imageData = 4
    case fps = 6
    case cameraPosition = 8
    case orientation = 10
    case timestamp = 12
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var hasImageData: Bool { let o = _accessor.offset(VTOFFSET.imageData.v); return o == 0 ? false : true }
  public var imageDataCount: Int32 { let o = _accessor.offset(VTOFFSET.imageData.v); return o == 0 ? 0 : _accessor.vector(count: o) }
  public func imageData(at index: Int32) -> UInt8 { let o = _accessor.offset(VTOFFSET.imageData.v); return o == 0 ? 0 : _accessor.directRead(of: UInt8.self, offset: _accessor.vector(at: o) + index * 1) }
  public var imageData: [UInt8] { return _accessor.getVector(at: VTOFFSET.imageData.v) ?? [] }
  public var fps: Int32 { let o = _accessor.offset(VTOFFSET.fps.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int32.self, at: o) }
  public var cameraPosition: RemoteShutter_CameraPosition { let o = _accessor.offset(VTOFFSET.cameraPosition.v); return o == 0 ? .back : RemoteShutter_CameraPosition(rawValue: _accessor.readBuffer(of: Int8.self, at: o)) ?? .back }
  public var orientation: String? { let o = _accessor.offset(VTOFFSET.orientation.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var orientationSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.orientation.v) }
  public var timestamp: UInt64 { let o = _accessor.offset(VTOFFSET.timestamp.v); return o == 0 ? 0 : _accessor.readBuffer(of: UInt64.self, at: o) }
  public static func startFrameData(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 5) }
  public static func addVectorOf(imageData: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: imageData, at: VTOFFSET.imageData.p) }
  public static func add(fps: Int32, _ fbb: inout FlatBufferBuilder) { fbb.add(element: fps, def: 0, at: VTOFFSET.fps.p) }
  public static func add(cameraPosition: RemoteShutter_CameraPosition, _ fbb: inout FlatBufferBuilder) { fbb.add(element: cameraPosition.rawValue, def: 0, at: VTOFFSET.cameraPosition.p) }
  public static func add(orientation: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: orientation, at: VTOFFSET.orientation.p) }
  public static func add(timestamp: UInt64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: timestamp, def: 0, at: VTOFFSET.timestamp.p) }
  public static func endFrameData(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createFrameData(
    _ fbb: inout FlatBufferBuilder,
    imageDataVectorOffset imageData: Offset = Offset(),
    fps: Int32 = 0,
    cameraPosition: RemoteShutter_CameraPosition = .back,
    orientationOffset orientation: Offset = Offset(),
    timestamp: UInt64 = 0
  ) -> Offset {
    let __start = RemoteShutter_FrameData.startFrameData(&fbb)
    RemoteShutter_FrameData.addVectorOf(imageData: imageData, &fbb)
    RemoteShutter_FrameData.add(fps: fps, &fbb)
    RemoteShutter_FrameData.add(cameraPosition: cameraPosition, &fbb)
    RemoteShutter_FrameData.add(orientation: orientation, &fbb)
    RemoteShutter_FrameData.add(timestamp: timestamp, &fbb)
    return RemoteShutter_FrameData.endFrameData(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.imageData.p, fieldName: "imageData", required: false, type: ForwardOffset<Vector<UInt8, UInt8>>.self)
    try _v.visit(field: VTOFFSET.fps.p, fieldName: "fps", required: false, type: Int32.self)
    try _v.visit(field: VTOFFSET.cameraPosition.p, fieldName: "cameraPosition", required: false, type: RemoteShutter_CameraPosition.self)
    try _v.visit(field: VTOFFSET.orientation.p, fieldName: "orientation", required: false, type: ForwardOffset<String>.self)
    try _v.visit(field: VTOFFSET.timestamp.p, fieldName: "timestamp", required: false, type: UInt64.self)
    _v.finish()
  }
}

public struct RemoteShutter_MediaData: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_25_2_10() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  public static var id: String { "RCAM" } 
  public static func finish(_ fbb: inout FlatBufferBuilder, end: Offset, prefix: Bool = false) { fbb.finish(offset: end, fileId: RemoteShutter_MediaData.id, addPrefix: prefix) }
  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case data = 4
    case type = 6
    case timestamp = 8
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var hasData: Bool { let o = _accessor.offset(VTOFFSET.data.v); return o == 0 ? false : true }
  public var dataCount: Int32 { let o = _accessor.offset(VTOFFSET.data.v); return o == 0 ? 0 : _accessor.vector(count: o) }
  public func data(at index: Int32) -> UInt8 { let o = _accessor.offset(VTOFFSET.data.v); return o == 0 ? 0 : _accessor.directRead(of: UInt8.self, offset: _accessor.vector(at: o) + index * 1) }
  public var data: [UInt8] { return _accessor.getVector(at: VTOFFSET.data.v) ?? [] }
  public var type: RemoteShutter_MediaType { let o = _accessor.offset(VTOFFSET.type.v); return o == 0 ? .photo : RemoteShutter_MediaType(rawValue: _accessor.readBuffer(of: Int8.self, at: o)) ?? .photo }
  public var timestamp: UInt64 { let o = _accessor.offset(VTOFFSET.timestamp.v); return o == 0 ? 0 : _accessor.readBuffer(of: UInt64.self, at: o) }
  public static func startMediaData(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 3) }
  public static func addVectorOf(data: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: data, at: VTOFFSET.data.p) }
  public static func add(type: RemoteShutter_MediaType, _ fbb: inout FlatBufferBuilder) { fbb.add(element: type.rawValue, def: 0, at: VTOFFSET.type.p) }
  public static func add(timestamp: UInt64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: timestamp, def: 0, at: VTOFFSET.timestamp.p) }
  public static func endMediaData(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createMediaData(
    _ fbb: inout FlatBufferBuilder,
    dataVectorOffset data: Offset = Offset(),
    type: RemoteShutter_MediaType = .photo,
    timestamp: UInt64 = 0
  ) -> Offset {
    let __start = RemoteShutter_MediaData.startMediaData(&fbb)
    RemoteShutter_MediaData.addVectorOf(data: data, &fbb)
    RemoteShutter_MediaData.add(type: type, &fbb)
    RemoteShutter_MediaData.add(timestamp: timestamp, &fbb)
    return RemoteShutter_MediaData.endMediaData(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.data.p, fieldName: "data", required: false, type: ForwardOffset<Vector<UInt8, UInt8>>.self)
    try _v.visit(field: VTOFFSET.type.p, fieldName: "type", required: false, type: RemoteShutter_MediaType.self)
    try _v.visit(field: VTOFFSET.timestamp.p, fieldName: "timestamp", required: false, type: UInt64.self)
    _v.finish()
  }
}

public struct RemoteShutter_Heartbeat: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_25_2_10() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  public static var id: String { "RCAM" } 
  public static func finish(_ fbb: inout FlatBufferBuilder, end: Offset, prefix: Bool = false) { fbb.finish(offset: end, fileId: RemoteShutter_Heartbeat.id, addPrefix: prefix) }
  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case timestamp = 4
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var timestamp: UInt64 { let o = _accessor.offset(VTOFFSET.timestamp.v); return o == 0 ? 0 : _accessor.readBuffer(of: UInt64.self, at: o) }
  public static func startHeartbeat(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 1) }
  public static func add(timestamp: UInt64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: timestamp, def: 0, at: VTOFFSET.timestamp.p) }
  public static func endHeartbeat(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createHeartbeat(
    _ fbb: inout FlatBufferBuilder,
    timestamp: UInt64 = 0
  ) -> Offset {
    let __start = RemoteShutter_Heartbeat.startHeartbeat(&fbb)
    RemoteShutter_Heartbeat.add(timestamp: timestamp, &fbb)
    return RemoteShutter_Heartbeat.endHeartbeat(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.timestamp.p, fieldName: "timestamp", required: false, type: UInt64.self)
    _v.finish()
  }
}

public struct RemoteShutter_ErrorMessage: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_25_2_10() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  public static var id: String { "RCAM" } 
  public static func finish(_ fbb: inout FlatBufferBuilder, end: Offset, prefix: Bool = false) { fbb.finish(offset: end, fileId: RemoteShutter_ErrorMessage.id, addPrefix: prefix) }
  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case code = 4
    case description = 6
    case timestamp = 8
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var code: Int32 { let o = _accessor.offset(VTOFFSET.code.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int32.self, at: o) }
  public var description: String? { let o = _accessor.offset(VTOFFSET.description.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var descriptionSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.description.v) }
  public var timestamp: UInt64 { let o = _accessor.offset(VTOFFSET.timestamp.v); return o == 0 ? 0 : _accessor.readBuffer(of: UInt64.self, at: o) }
  public static func startErrorMessage(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 3) }
  public static func add(code: Int32, _ fbb: inout FlatBufferBuilder) { fbb.add(element: code, def: 0, at: VTOFFSET.code.p) }
  public static func add(description: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: description, at: VTOFFSET.description.p) }
  public static func add(timestamp: UInt64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: timestamp, def: 0, at: VTOFFSET.timestamp.p) }
  public static func endErrorMessage(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createErrorMessage(
    _ fbb: inout FlatBufferBuilder,
    code: Int32 = 0,
    descriptionOffset description: Offset = Offset(),
    timestamp: UInt64 = 0
  ) -> Offset {
    let __start = RemoteShutter_ErrorMessage.startErrorMessage(&fbb)
    RemoteShutter_ErrorMessage.add(code: code, &fbb)
    RemoteShutter_ErrorMessage.add(description: description, &fbb)
    RemoteShutter_ErrorMessage.add(timestamp: timestamp, &fbb)
    return RemoteShutter_ErrorMessage.endErrorMessage(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.code.p, fieldName: "code", required: false, type: Int32.self)
    try _v.visit(field: VTOFFSET.description.p, fieldName: "description", required: false, type: ForwardOffset<String>.self)
    try _v.visit(field: VTOFFSET.timestamp.p, fieldName: "timestamp", required: false, type: UInt64.self)
    _v.finish()
  }
}

public struct RemoteShutter_P2PMessage: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_25_2_10() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  public static var id: String { "RCAM" } 
  public static func finish(_ fbb: inout FlatBufferBuilder, end: Offset, prefix: Bool = false) { fbb.finish(offset: end, fileId: RemoteShutter_P2PMessage.id, addPrefix: prefix) }
  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case id = 4
    case timestamp = 6
    case type = 8
    case sender = 10
    case command = 12
    case response = 14
    case frameData = 16
    case mediaData = 18
    case heartbeat = 20
    case errorMessage = 22
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var id: String? { let o = _accessor.offset(VTOFFSET.id.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var idSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.id.v) }
  public var timestamp: UInt64 { let o = _accessor.offset(VTOFFSET.timestamp.v); return o == 0 ? 0 : _accessor.readBuffer(of: UInt64.self, at: o) }
  public var type: RemoteShutter_MessageType { let o = _accessor.offset(VTOFFSET.type.v); return o == 0 ? .cameracommand : RemoteShutter_MessageType(rawValue: _accessor.readBuffer(of: Int8.self, at: o)) ?? .cameracommand }
  public var sender: String? { let o = _accessor.offset(VTOFFSET.sender.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var senderSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.sender.v) }
  public var command: RemoteShutter_CameraCommand? { let o = _accessor.offset(VTOFFSET.command.v); return o == 0 ? nil : RemoteShutter_CameraCommand(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public var response: RemoteShutter_CameraStateResponse? { let o = _accessor.offset(VTOFFSET.response.v); return o == 0 ? nil : RemoteShutter_CameraStateResponse(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public var frameData: RemoteShutter_FrameData? { let o = _accessor.offset(VTOFFSET.frameData.v); return o == 0 ? nil : RemoteShutter_FrameData(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public var mediaData: RemoteShutter_MediaData? { let o = _accessor.offset(VTOFFSET.mediaData.v); return o == 0 ? nil : RemoteShutter_MediaData(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public var heartbeat: RemoteShutter_Heartbeat? { let o = _accessor.offset(VTOFFSET.heartbeat.v); return o == 0 ? nil : RemoteShutter_Heartbeat(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public var errorMessage: RemoteShutter_ErrorMessage? { let o = _accessor.offset(VTOFFSET.errorMessage.v); return o == 0 ? nil : RemoteShutter_ErrorMessage(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public static func startP2PMessage(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 10) }
  public static func add(id: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: id, at: VTOFFSET.id.p) }
  public static func add(timestamp: UInt64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: timestamp, def: 0, at: VTOFFSET.timestamp.p) }
  public static func add(type: RemoteShutter_MessageType, _ fbb: inout FlatBufferBuilder) { fbb.add(element: type.rawValue, def: 0, at: VTOFFSET.type.p) }
  public static func add(sender: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: sender, at: VTOFFSET.sender.p) }
  public static func add(command: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: command, at: VTOFFSET.command.p) }
  public static func add(response: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: response, at: VTOFFSET.response.p) }
  public static func add(frameData: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: frameData, at: VTOFFSET.frameData.p) }
  public static func add(mediaData: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: mediaData, at: VTOFFSET.mediaData.p) }
  public static func add(heartbeat: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: heartbeat, at: VTOFFSET.heartbeat.p) }
  public static func add(errorMessage: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: errorMessage, at: VTOFFSET.errorMessage.p) }
  public static func endP2PMessage(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createP2PMessage(
    _ fbb: inout FlatBufferBuilder,
    idOffset id: Offset = Offset(),
    timestamp: UInt64 = 0,
    type: RemoteShutter_MessageType = .cameracommand,
    senderOffset sender: Offset = Offset(),
    commandOffset command: Offset = Offset(),
    responseOffset response: Offset = Offset(),
    frameDataOffset frameData: Offset = Offset(),
    mediaDataOffset mediaData: Offset = Offset(),
    heartbeatOffset heartbeat: Offset = Offset(),
    errorMessageOffset errorMessage: Offset = Offset()
  ) -> Offset {
    let __start = RemoteShutter_P2PMessage.startP2PMessage(&fbb)
    RemoteShutter_P2PMessage.add(id: id, &fbb)
    RemoteShutter_P2PMessage.add(timestamp: timestamp, &fbb)
    RemoteShutter_P2PMessage.add(type: type, &fbb)
    RemoteShutter_P2PMessage.add(sender: sender, &fbb)
    RemoteShutter_P2PMessage.add(command: command, &fbb)
    RemoteShutter_P2PMessage.add(response: response, &fbb)
    RemoteShutter_P2PMessage.add(frameData: frameData, &fbb)
    RemoteShutter_P2PMessage.add(mediaData: mediaData, &fbb)
    RemoteShutter_P2PMessage.add(heartbeat: heartbeat, &fbb)
    RemoteShutter_P2PMessage.add(errorMessage: errorMessage, &fbb)
    return RemoteShutter_P2PMessage.endP2PMessage(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.id.p, fieldName: "id", required: false, type: ForwardOffset<String>.self)
    try _v.visit(field: VTOFFSET.timestamp.p, fieldName: "timestamp", required: false, type: UInt64.self)
    try _v.visit(field: VTOFFSET.type.p, fieldName: "type", required: false, type: RemoteShutter_MessageType.self)
    try _v.visit(field: VTOFFSET.sender.p, fieldName: "sender", required: false, type: ForwardOffset<String>.self)
    try _v.visit(field: VTOFFSET.command.p, fieldName: "command", required: false, type: ForwardOffset<RemoteShutter_CameraCommand>.self)
    try _v.visit(field: VTOFFSET.response.p, fieldName: "response", required: false, type: ForwardOffset<RemoteShutter_CameraStateResponse>.self)
    try _v.visit(field: VTOFFSET.frameData.p, fieldName: "frameData", required: false, type: ForwardOffset<RemoteShutter_FrameData>.self)
    try _v.visit(field: VTOFFSET.mediaData.p, fieldName: "mediaData", required: false, type: ForwardOffset<RemoteShutter_MediaData>.self)
    try _v.visit(field: VTOFFSET.heartbeat.p, fieldName: "heartbeat", required: false, type: ForwardOffset<RemoteShutter_Heartbeat>.self)
    try _v.visit(field: VTOFFSET.errorMessage.p, fieldName: "errorMessage", required: false, type: ForwardOffset<RemoteShutter_ErrorMessage>.self)
    _v.finish()
  }
}

